/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => GCommandPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  rcloneRemote: "gdrive",
  rclonePath: "",
  vaultRoot: "gdrive",
  selectedPaths: [],
  syncState: {},
  frontmatterGdriveFields: true,
  driveCache: null
};

// src/GDriveSidebar.ts
var import_obsidian2 = require("obsidian");

// src/DriveProvider.ts
var import_child_process = require("child_process");
var import_fs = require("fs");
var import_path = require("path");
var import_os = require("os");
var MAX_BUFFER = 50 * 1024 * 1024;
var TAG = "[G Command]";
var RCLONE_SEARCH_PATHS = [
  "/opt/homebrew/bin/rclone",
  // macOS ARM Homebrew
  "/usr/local/bin/rclone",
  // macOS Intel Homebrew / manual install
  "/usr/bin/rclone",
  // Linux package manager
  "rclone"
  // fallback: bare name (works if PATH is set)
];
var DriveError = class extends Error {
  constructor(code, message) {
    super(message);
    this.code = code;
    this.name = "DriveError";
  }
};
var DriveProvider = class {
  constructor(remote) {
    this.remote = remote;
    this.rclonePath = null;
    this.explicitPath = null;
  }
  /** Update the remote name (e.g. after settings change). */
  setRemote(remote) {
    this.remote = remote;
  }
  /**
   * Lists files and folders one level deep at the given Drive path.
   * Pass an empty string to list the Drive root.
   */
  async list(drivePath) {
    const remotePath = drivePath ? `${this.remote}:${drivePath}` : `${this.remote}:`;
    const output = await this.run(["lsjson", remotePath, "--max-depth", "1"]);
    return JSON.parse(output);
  }
  /**
   * Recursively lists all files (not folders) under the given Drive path.
   * Used by SyncManager to expand folder selections before syncing.
   */
  async listRecursive(drivePath) {
    const remotePath = drivePath ? `${this.remote}:${drivePath}` : `${this.remote}:`;
    const output = await this.run([
      "lsjson",
      remotePath,
      "--recursive",
      "--files-only"
    ]);
    return JSON.parse(output);
  }
  /**
   * Downloads a single file and returns its content as a string.
   *
   * Uses `rclone copy --include <filename>` from the parent directory.
   * Google Workspace virtual files can't be addressed by full path (rclone
   * treats them as directories), but they CAN be found via directory listing
   * with an include filter. For exports, the filter uses the target extension
   * (e.g. .html) since --drive-export-formats changes the virtual filename.
   *
   * For Google Workspace files, pass an exportFormat (e.g. "html" for Docs,
   * "csv" for Sheets). For regular files, omit exportFormat.
   */
  async download(drivePath, exportFormat) {
    const tmpDir = (0, import_fs.mkdtempSync)((0, import_path.join)((0, import_os.tmpdir)(), "gc-"));
    try {
      const lastSlash = drivePath.lastIndexOf("/");
      const parentDir = lastSlash > 0 ? drivePath.substring(0, lastSlash) : "";
      const fileName = lastSlash > 0 ? drivePath.substring(lastSlash + 1) : drivePath;
      let includeFilter = fileName;
      if (exportFormat) {
        const dotIdx = fileName.lastIndexOf(".");
        const baseName = dotIdx > 0 ? fileName.substring(0, dotIdx) : fileName;
        includeFilter = `${baseName}.${exportFormat}`;
      }
      includeFilter = includeFilter.replace(/([[\]*?{}])/g, "\\$1");
      const remotePath = parentDir ? `${this.remote}:${parentDir}` : `${this.remote}:`;
      const args = ["copy", "--include", includeFilter];
      if (exportFormat) {
        args.push("--drive-export-formats", exportFormat);
      }
      args.push(remotePath, tmpDir);
      console.log(TAG, `download args: [${args.map((a) => `"${a}"`).join(", ")}]`);
      await this.run(args);
      const files = (0, import_fs.readdirSync)(tmpDir);
      console.log(TAG, `download tmpDir contents: [${files.join(", ")}] (${files.length} file(s))`);
      if (files.length === 0) {
        throw new Error(
          `rclone copy produced no output for "${drivePath}" (include="${includeFilter}", exportFormat=${exportFormat != null ? exportFormat : "none"})`
        );
      }
      const outPath = (0, import_path.join)(tmpDir, files[0]);
      const raw = (0, import_fs.readFileSync)(outPath, "utf-8");
      const fileSize = raw.length;
      const preview = raw.substring(0, 200).replace(/\n/g, "\\n");
      console.log(TAG, `download result: file="${files[0]}", size=${fileSize}, preview="${preview}\u2026"`);
      return raw;
    } finally {
      try {
        (0, import_fs.rmSync)(tmpDir, { recursive: true, force: true });
      } catch (e) {
      }
    }
  }
  /**
   * Verifies that rclone is installed and the configured remote is reachable.
   * Throws a descriptive Error if either check fails.
   * Called once on plugin load and before each sync.
   */
  async check() {
    await this.checkBinary();
    await this.checkRemote();
  }
  /**
   * Create (or re-create) the rclone remote for Google Drive via non-interactive config.
   * Opens a browser for Google OAuth — the only user interaction.
   * Returns a result object instead of throwing, so the UI can differentiate failure modes.
   */
  async setupRemote(remoteName) {
    const name = remoteName || this.remote;
    try {
      await this.checkBinary();
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      return { ok: false, code: "binary-missing", message: msg };
    }
    try {
      await new Promise((resolve, reject) => {
        (0, import_child_process.execFile)(
          this.rclonePath,
          [
            "config",
            "create",
            name,
            "drive",
            "scope=drive.readonly",
            "config_is_local=true",
            "config_change_team_drive=false"
          ],
          { maxBuffer: MAX_BUFFER, timeout: 12e4 },
          (err2, _stdout, stderr) => {
            if (err2) {
              const detail = (stderr == null ? void 0 : stderr.trim()) || err2.message;
              return reject(Object.assign(err2, { detail }));
            }
            resolve();
          }
        );
      });
    } catch (e) {
      const err2 = e;
      if (err2.killed) {
        return { ok: false, code: "timeout", message: "Sign-in timed out. Try again." };
      }
      const detail = err2.detail || err2.message;
      console.error(TAG, "setupRemote config create failed:", detail);
      return { ok: false, code: "setup-failed", message: `Setup failed: ${detail}` };
    }
    try {
      await this.checkRemote();
      console.log(TAG, `Remote "${name}" created and verified`);
      return { ok: true };
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      console.error(TAG, "Remote created but verification failed:", msg);
      return { ok: false, code: "setup-failed", message: `Remote created but verification failed: ${msg}` };
    }
  }
  /** Set an explicit binary path override. Empty string = auto-detect. */
  setPath(path) {
    this.explicitPath = path || null;
  }
  async checkBinary() {
    this.rclonePath = null;
    if (this.explicitPath) {
      try {
        const version = await this.tryBinary(this.explicitPath);
        this.rclonePath = this.explicitPath;
        console.log(TAG, `rclone found at ${this.explicitPath} (configured):`, version);
        return;
      } catch (e) {
        console.error(TAG, `Configured rclone path not usable: ${this.explicitPath}`);
        throw new DriveError(
          "binary-missing",
          `rclone not found at configured path: ${this.explicitPath}`
        );
      }
    }
    for (const candidate of RCLONE_SEARCH_PATHS) {
      if (!candidate.includes("/") || (0, import_fs.existsSync)(candidate)) {
        try {
          const version = await this.tryBinary(candidate);
          this.rclonePath = candidate;
          console.log(TAG, `rclone found at ${candidate}:`, version);
          return;
        } catch (e) {
          console.log(TAG, `rclone not usable at ${candidate}`);
        }
      }
    }
    console.error(TAG, "rclone not found in any search path:", RCLONE_SEARCH_PATHS.join(", "));
    throw new DriveError(
      "binary-missing",
      "rclone is not installed (not found in PATH or common Homebrew locations)."
    );
  }
  tryBinary(bin) {
    return new Promise((resolve, reject) => {
      (0, import_child_process.execFile)(bin, ["version"], { maxBuffer: MAX_BUFFER }, (err2, stdout) => {
        var _a;
        if (err2)
          return reject(err2);
        resolve((_a = stdout.split("\n")[0]) != null ? _a : "unknown");
      });
    });
  }
  async checkRemote() {
    return new Promise((resolve, reject) => {
      console.log(TAG, `Checking remote "${this.remote}"\u2026`);
      (0, import_child_process.execFile)(
        this.rclonePath,
        ["lsjson", `${this.remote}:`, "--max-depth", "1", "--files-only"],
        { maxBuffer: MAX_BUFFER },
        (err2, _stdout, stderr) => {
          if (err2) {
            const detail = (stderr == null ? void 0 : stderr.trim()) || err2.message;
            console.error(TAG, `Remote "${this.remote}" check failed:`, detail);
            reject(
              new DriveError(
                "remote-unreachable",
                `Remote "${this.remote}" is not reachable: ${detail}`
              )
            );
          } else {
            console.log(TAG, `Remote "${this.remote}" connected`);
            resolve();
          }
        }
      );
    });
  }
  run(args) {
    if (!this.rclonePath) {
      return Promise.reject(new DriveError("binary-missing", "rclone path not resolved \u2014 call check() first."));
    }
    return new Promise((resolve, reject) => {
      (0, import_child_process.execFile)(this.rclonePath, args, { maxBuffer: MAX_BUFFER }, (err2, stdout, stderr) => {
        if (err2) {
          const detail = (stderr == null ? void 0 : stderr.trim()) || err2.message;
          console.error(TAG, `rclone ${args[0]} failed:`, detail);
          return reject(err2);
        }
        resolve(stdout);
      });
    });
  }
};
function getRcloneInstallInstructions() {
  const platform = process.platform;
  if (platform === "darwin") {
    return {
      command: "brew install rclone",
      label: "macOS (Homebrew)",
      url: "https://rclone.org/install/#macos-homebrew"
    };
  } else if (platform === "linux") {
    return {
      command: "curl https://rclone.org/install.sh | sudo bash",
      label: "Linux",
      url: "https://rclone.org/install/#linux"
    };
  }
  return {
    command: "winget install Rclone.Rclone",
    label: "Windows",
    url: "https://rclone.org/install/#windows"
  };
}

// src/SyncManager.ts
var import_obsidian = require("obsidian");

// node_modules/turndown/lib/turndown.browser.es.js
function extend(destination) {
  for (var i = 1; i < arguments.length; i++) {
    var source = arguments[i];
    for (var key in source) {
      if (source.hasOwnProperty(key))
        destination[key] = source[key];
    }
  }
  return destination;
}
function repeat(character, count) {
  return Array(count + 1).join(character);
}
function trimLeadingNewlines(string) {
  return string.replace(/^\n*/, "");
}
function trimTrailingNewlines(string) {
  var indexEnd = string.length;
  while (indexEnd > 0 && string[indexEnd - 1] === "\n")
    indexEnd--;
  return string.substring(0, indexEnd);
}
function trimNewlines(string) {
  return trimTrailingNewlines(trimLeadingNewlines(string));
}
var blockElements = [
  "ADDRESS",
  "ARTICLE",
  "ASIDE",
  "AUDIO",
  "BLOCKQUOTE",
  "BODY",
  "CANVAS",
  "CENTER",
  "DD",
  "DIR",
  "DIV",
  "DL",
  "DT",
  "FIELDSET",
  "FIGCAPTION",
  "FIGURE",
  "FOOTER",
  "FORM",
  "FRAMESET",
  "H1",
  "H2",
  "H3",
  "H4",
  "H5",
  "H6",
  "HEADER",
  "HGROUP",
  "HR",
  "HTML",
  "ISINDEX",
  "LI",
  "MAIN",
  "MENU",
  "NAV",
  "NOFRAMES",
  "NOSCRIPT",
  "OL",
  "OUTPUT",
  "P",
  "PRE",
  "SECTION",
  "TABLE",
  "TBODY",
  "TD",
  "TFOOT",
  "TH",
  "THEAD",
  "TR",
  "UL"
];
function isBlock(node) {
  return is(node, blockElements);
}
var voidElements = [
  "AREA",
  "BASE",
  "BR",
  "COL",
  "COMMAND",
  "EMBED",
  "HR",
  "IMG",
  "INPUT",
  "KEYGEN",
  "LINK",
  "META",
  "PARAM",
  "SOURCE",
  "TRACK",
  "WBR"
];
function isVoid(node) {
  return is(node, voidElements);
}
function hasVoid(node) {
  return has(node, voidElements);
}
var meaningfulWhenBlankElements = [
  "A",
  "TABLE",
  "THEAD",
  "TBODY",
  "TFOOT",
  "TH",
  "TD",
  "IFRAME",
  "SCRIPT",
  "AUDIO",
  "VIDEO"
];
function isMeaningfulWhenBlank(node) {
  return is(node, meaningfulWhenBlankElements);
}
function hasMeaningfulWhenBlank(node) {
  return has(node, meaningfulWhenBlankElements);
}
function is(node, tagNames) {
  return tagNames.indexOf(node.nodeName) >= 0;
}
function has(node, tagNames) {
  return node.getElementsByTagName && tagNames.some(function(tagName) {
    return node.getElementsByTagName(tagName).length;
  });
}
var rules = {};
rules.paragraph = {
  filter: "p",
  replacement: function(content) {
    return "\n\n" + content + "\n\n";
  }
};
rules.lineBreak = {
  filter: "br",
  replacement: function(content, node, options) {
    return options.br + "\n";
  }
};
rules.heading = {
  filter: ["h1", "h2", "h3", "h4", "h5", "h6"],
  replacement: function(content, node, options) {
    var hLevel = Number(node.nodeName.charAt(1));
    if (options.headingStyle === "setext" && hLevel < 3) {
      var underline = repeat(hLevel === 1 ? "=" : "-", content.length);
      return "\n\n" + content + "\n" + underline + "\n\n";
    } else {
      return "\n\n" + repeat("#", hLevel) + " " + content + "\n\n";
    }
  }
};
rules.blockquote = {
  filter: "blockquote",
  replacement: function(content) {
    content = trimNewlines(content).replace(/^/gm, "> ");
    return "\n\n" + content + "\n\n";
  }
};
rules.list = {
  filter: ["ul", "ol"],
  replacement: function(content, node) {
    var parent = node.parentNode;
    if (parent.nodeName === "LI" && parent.lastElementChild === node) {
      return "\n" + content;
    } else {
      return "\n\n" + content + "\n\n";
    }
  }
};
rules.listItem = {
  filter: "li",
  replacement: function(content, node, options) {
    var prefix = options.bulletListMarker + "   ";
    var parent = node.parentNode;
    if (parent.nodeName === "OL") {
      var start = parent.getAttribute("start");
      var index = Array.prototype.indexOf.call(parent.children, node);
      prefix = (start ? Number(start) + index : index + 1) + ".  ";
    }
    var isParagraph = /\n$/.test(content);
    content = trimNewlines(content) + (isParagraph ? "\n" : "");
    content = content.replace(/\n/gm, "\n" + " ".repeat(prefix.length));
    return prefix + content + (node.nextSibling ? "\n" : "");
  }
};
rules.indentedCodeBlock = {
  filter: function(node, options) {
    return options.codeBlockStyle === "indented" && node.nodeName === "PRE" && node.firstChild && node.firstChild.nodeName === "CODE";
  },
  replacement: function(content, node, options) {
    return "\n\n    " + node.firstChild.textContent.replace(/\n/g, "\n    ") + "\n\n";
  }
};
rules.fencedCodeBlock = {
  filter: function(node, options) {
    return options.codeBlockStyle === "fenced" && node.nodeName === "PRE" && node.firstChild && node.firstChild.nodeName === "CODE";
  },
  replacement: function(content, node, options) {
    var className = node.firstChild.getAttribute("class") || "";
    var language = (className.match(/language-(\S+)/) || [null, ""])[1];
    var code = node.firstChild.textContent;
    var fenceChar = options.fence.charAt(0);
    var fenceSize = 3;
    var fenceInCodeRegex = new RegExp("^" + fenceChar + "{3,}", "gm");
    var match;
    while (match = fenceInCodeRegex.exec(code)) {
      if (match[0].length >= fenceSize) {
        fenceSize = match[0].length + 1;
      }
    }
    var fence = repeat(fenceChar, fenceSize);
    return "\n\n" + fence + language + "\n" + code.replace(/\n$/, "") + "\n" + fence + "\n\n";
  }
};
rules.horizontalRule = {
  filter: "hr",
  replacement: function(content, node, options) {
    return "\n\n" + options.hr + "\n\n";
  }
};
rules.inlineLink = {
  filter: function(node, options) {
    return options.linkStyle === "inlined" && node.nodeName === "A" && node.getAttribute("href");
  },
  replacement: function(content, node) {
    var href = node.getAttribute("href");
    if (href)
      href = href.replace(/([()])/g, "\\$1");
    var title = cleanAttribute(node.getAttribute("title"));
    if (title)
      title = ' "' + title.replace(/"/g, '\\"') + '"';
    return "[" + content + "](" + href + title + ")";
  }
};
rules.referenceLink = {
  filter: function(node, options) {
    return options.linkStyle === "referenced" && node.nodeName === "A" && node.getAttribute("href");
  },
  replacement: function(content, node, options) {
    var href = node.getAttribute("href");
    var title = cleanAttribute(node.getAttribute("title"));
    if (title)
      title = ' "' + title + '"';
    var replacement;
    var reference;
    switch (options.linkReferenceStyle) {
      case "collapsed":
        replacement = "[" + content + "][]";
        reference = "[" + content + "]: " + href + title;
        break;
      case "shortcut":
        replacement = "[" + content + "]";
        reference = "[" + content + "]: " + href + title;
        break;
      default:
        var id = this.references.length + 1;
        replacement = "[" + content + "][" + id + "]";
        reference = "[" + id + "]: " + href + title;
    }
    this.references.push(reference);
    return replacement;
  },
  references: [],
  append: function(options) {
    var references = "";
    if (this.references.length) {
      references = "\n\n" + this.references.join("\n") + "\n\n";
      this.references = [];
    }
    return references;
  }
};
rules.emphasis = {
  filter: ["em", "i"],
  replacement: function(content, node, options) {
    if (!content.trim())
      return "";
    return options.emDelimiter + content + options.emDelimiter;
  }
};
rules.strong = {
  filter: ["strong", "b"],
  replacement: function(content, node, options) {
    if (!content.trim())
      return "";
    return options.strongDelimiter + content + options.strongDelimiter;
  }
};
rules.code = {
  filter: function(node) {
    var hasSiblings = node.previousSibling || node.nextSibling;
    var isCodeBlock = node.parentNode.nodeName === "PRE" && !hasSiblings;
    return node.nodeName === "CODE" && !isCodeBlock;
  },
  replacement: function(content) {
    if (!content)
      return "";
    content = content.replace(/\r?\n|\r/g, " ");
    var extraSpace = /^`|^ .*?[^ ].* $|`$/.test(content) ? " " : "";
    var delimiter = "`";
    var matches = content.match(/`+/gm) || [];
    while (matches.indexOf(delimiter) !== -1)
      delimiter = delimiter + "`";
    return delimiter + extraSpace + content + extraSpace + delimiter;
  }
};
rules.image = {
  filter: "img",
  replacement: function(content, node) {
    var alt = cleanAttribute(node.getAttribute("alt"));
    var src = node.getAttribute("src") || "";
    var title = cleanAttribute(node.getAttribute("title"));
    var titlePart = title ? ' "' + title + '"' : "";
    return src ? "![" + alt + "](" + src + titlePart + ")" : "";
  }
};
function cleanAttribute(attribute) {
  return attribute ? attribute.replace(/(\n+\s*)+/g, "\n") : "";
}
function Rules(options) {
  this.options = options;
  this._keep = [];
  this._remove = [];
  this.blankRule = {
    replacement: options.blankReplacement
  };
  this.keepReplacement = options.keepReplacement;
  this.defaultRule = {
    replacement: options.defaultReplacement
  };
  this.array = [];
  for (var key in options.rules)
    this.array.push(options.rules[key]);
}
Rules.prototype = {
  add: function(key, rule) {
    this.array.unshift(rule);
  },
  keep: function(filter) {
    this._keep.unshift({
      filter,
      replacement: this.keepReplacement
    });
  },
  remove: function(filter) {
    this._remove.unshift({
      filter,
      replacement: function() {
        return "";
      }
    });
  },
  forNode: function(node) {
    if (node.isBlank)
      return this.blankRule;
    var rule;
    if (rule = findRule(this.array, node, this.options))
      return rule;
    if (rule = findRule(this._keep, node, this.options))
      return rule;
    if (rule = findRule(this._remove, node, this.options))
      return rule;
    return this.defaultRule;
  },
  forEach: function(fn) {
    for (var i = 0; i < this.array.length; i++)
      fn(this.array[i], i);
  }
};
function findRule(rules2, node, options) {
  for (var i = 0; i < rules2.length; i++) {
    var rule = rules2[i];
    if (filterValue(rule, node, options))
      return rule;
  }
  return void 0;
}
function filterValue(rule, node, options) {
  var filter = rule.filter;
  if (typeof filter === "string") {
    if (filter === node.nodeName.toLowerCase())
      return true;
  } else if (Array.isArray(filter)) {
    if (filter.indexOf(node.nodeName.toLowerCase()) > -1)
      return true;
  } else if (typeof filter === "function") {
    if (filter.call(rule, node, options))
      return true;
  } else {
    throw new TypeError("`filter` needs to be a string, array, or function");
  }
}
function collapseWhitespace(options) {
  var element = options.element;
  var isBlock2 = options.isBlock;
  var isVoid2 = options.isVoid;
  var isPre = options.isPre || function(node2) {
    return node2.nodeName === "PRE";
  };
  if (!element.firstChild || isPre(element))
    return;
  var prevText = null;
  var keepLeadingWs = false;
  var prev = null;
  var node = next(prev, element, isPre);
  while (node !== element) {
    if (node.nodeType === 3 || node.nodeType === 4) {
      var text = node.data.replace(/[ \r\n\t]+/g, " ");
      if ((!prevText || / $/.test(prevText.data)) && !keepLeadingWs && text[0] === " ") {
        text = text.substr(1);
      }
      if (!text) {
        node = remove(node);
        continue;
      }
      node.data = text;
      prevText = node;
    } else if (node.nodeType === 1) {
      if (isBlock2(node) || node.nodeName === "BR") {
        if (prevText) {
          prevText.data = prevText.data.replace(/ $/, "");
        }
        prevText = null;
        keepLeadingWs = false;
      } else if (isVoid2(node) || isPre(node)) {
        prevText = null;
        keepLeadingWs = true;
      } else if (prevText) {
        keepLeadingWs = false;
      }
    } else {
      node = remove(node);
      continue;
    }
    var nextNode = next(prev, node, isPre);
    prev = node;
    node = nextNode;
  }
  if (prevText) {
    prevText.data = prevText.data.replace(/ $/, "");
    if (!prevText.data) {
      remove(prevText);
    }
  }
}
function remove(node) {
  var next2 = node.nextSibling || node.parentNode;
  node.parentNode.removeChild(node);
  return next2;
}
function next(prev, current, isPre) {
  if (prev && prev.parentNode === current || isPre(current)) {
    return current.nextSibling || current.parentNode;
  }
  return current.firstChild || current.nextSibling || current.parentNode;
}
var root = typeof window !== "undefined" ? window : {};
function canParseHTMLNatively() {
  var Parser = root.DOMParser;
  var canParse = false;
  try {
    if (new Parser().parseFromString("", "text/html")) {
      canParse = true;
    }
  } catch (e) {
  }
  return canParse;
}
function createHTMLParser() {
  var Parser = function() {
  };
  {
    if (shouldUseActiveX()) {
      Parser.prototype.parseFromString = function(string) {
        var doc = new window.ActiveXObject("htmlfile");
        doc.designMode = "on";
        doc.open();
        doc.write(string);
        doc.close();
        return doc;
      };
    } else {
      Parser.prototype.parseFromString = function(string) {
        var doc = document.implementation.createHTMLDocument("");
        doc.open();
        doc.write(string);
        doc.close();
        return doc;
      };
    }
  }
  return Parser;
}
function shouldUseActiveX() {
  var useActiveX = false;
  try {
    document.implementation.createHTMLDocument("").open();
  } catch (e) {
    if (root.ActiveXObject)
      useActiveX = true;
  }
  return useActiveX;
}
var HTMLParser = canParseHTMLNatively() ? root.DOMParser : createHTMLParser();
function RootNode(input, options) {
  var root2;
  if (typeof input === "string") {
    var doc = htmlParser().parseFromString(
      // DOM parsers arrange elements in the <head> and <body>.
      // Wrapping in a custom element ensures elements are reliably arranged in
      // a single element.
      '<x-turndown id="turndown-root">' + input + "</x-turndown>",
      "text/html"
    );
    root2 = doc.getElementById("turndown-root");
  } else {
    root2 = input.cloneNode(true);
  }
  collapseWhitespace({
    element: root2,
    isBlock,
    isVoid,
    isPre: options.preformattedCode ? isPreOrCode : null
  });
  return root2;
}
var _htmlParser;
function htmlParser() {
  _htmlParser = _htmlParser || new HTMLParser();
  return _htmlParser;
}
function isPreOrCode(node) {
  return node.nodeName === "PRE" || node.nodeName === "CODE";
}
function Node(node, options) {
  node.isBlock = isBlock(node);
  node.isCode = node.nodeName === "CODE" || node.parentNode.isCode;
  node.isBlank = isBlank(node);
  node.flankingWhitespace = flankingWhitespace(node, options);
  return node;
}
function isBlank(node) {
  return !isVoid(node) && !isMeaningfulWhenBlank(node) && /^\s*$/i.test(node.textContent) && !hasVoid(node) && !hasMeaningfulWhenBlank(node);
}
function flankingWhitespace(node, options) {
  if (node.isBlock || options.preformattedCode && node.isCode) {
    return { leading: "", trailing: "" };
  }
  var edges = edgeWhitespace(node.textContent);
  if (edges.leadingAscii && isFlankedByWhitespace("left", node, options)) {
    edges.leading = edges.leadingNonAscii;
  }
  if (edges.trailingAscii && isFlankedByWhitespace("right", node, options)) {
    edges.trailing = edges.trailingNonAscii;
  }
  return { leading: edges.leading, trailing: edges.trailing };
}
function edgeWhitespace(string) {
  var m = string.match(/^(([ \t\r\n]*)(\s*))(?:(?=\S)[\s\S]*\S)?((\s*?)([ \t\r\n]*))$/);
  return {
    leading: m[1],
    // whole string for whitespace-only strings
    leadingAscii: m[2],
    leadingNonAscii: m[3],
    trailing: m[4],
    // empty for whitespace-only strings
    trailingNonAscii: m[5],
    trailingAscii: m[6]
  };
}
function isFlankedByWhitespace(side, node, options) {
  var sibling;
  var regExp;
  var isFlanked;
  if (side === "left") {
    sibling = node.previousSibling;
    regExp = / $/;
  } else {
    sibling = node.nextSibling;
    regExp = /^ /;
  }
  if (sibling) {
    if (sibling.nodeType === 3) {
      isFlanked = regExp.test(sibling.nodeValue);
    } else if (options.preformattedCode && sibling.nodeName === "CODE") {
      isFlanked = false;
    } else if (sibling.nodeType === 1 && !isBlock(sibling)) {
      isFlanked = regExp.test(sibling.textContent);
    }
  }
  return isFlanked;
}
var reduce = Array.prototype.reduce;
var escapes = [
  [/\\/g, "\\\\"],
  [/\*/g, "\\*"],
  [/^-/g, "\\-"],
  [/^\+ /g, "\\+ "],
  [/^(=+)/g, "\\$1"],
  [/^(#{1,6}) /g, "\\$1 "],
  [/`/g, "\\`"],
  [/^~~~/g, "\\~~~"],
  [/\[/g, "\\["],
  [/\]/g, "\\]"],
  [/^>/g, "\\>"],
  [/_/g, "\\_"],
  [/^(\d+)\. /g, "$1\\. "]
];
function TurndownService(options) {
  if (!(this instanceof TurndownService))
    return new TurndownService(options);
  var defaults = {
    rules,
    headingStyle: "setext",
    hr: "* * *",
    bulletListMarker: "*",
    codeBlockStyle: "indented",
    fence: "```",
    emDelimiter: "_",
    strongDelimiter: "**",
    linkStyle: "inlined",
    linkReferenceStyle: "full",
    br: "  ",
    preformattedCode: false,
    blankReplacement: function(content, node) {
      return node.isBlock ? "\n\n" : "";
    },
    keepReplacement: function(content, node) {
      return node.isBlock ? "\n\n" + node.outerHTML + "\n\n" : node.outerHTML;
    },
    defaultReplacement: function(content, node) {
      return node.isBlock ? "\n\n" + content + "\n\n" : content;
    }
  };
  this.options = extend({}, defaults, options);
  this.rules = new Rules(this.options);
}
TurndownService.prototype = {
  /**
   * The entry point for converting a string or DOM node to Markdown
   * @public
   * @param {String|HTMLElement} input The string or DOM node to convert
   * @returns A Markdown representation of the input
   * @type String
   */
  turndown: function(input) {
    if (!canConvert(input)) {
      throw new TypeError(
        input + " is not a string, or an element/document/fragment node."
      );
    }
    if (input === "")
      return "";
    var output = process2.call(this, new RootNode(input, this.options));
    return postProcess.call(this, output);
  },
  /**
   * Add one or more plugins
   * @public
   * @param {Function|Array} plugin The plugin or array of plugins to add
   * @returns The Turndown instance for chaining
   * @type Object
   */
  use: function(plugin) {
    if (Array.isArray(plugin)) {
      for (var i = 0; i < plugin.length; i++)
        this.use(plugin[i]);
    } else if (typeof plugin === "function") {
      plugin(this);
    } else {
      throw new TypeError("plugin must be a Function or an Array of Functions");
    }
    return this;
  },
  /**
   * Adds a rule
   * @public
   * @param {String} key The unique key of the rule
   * @param {Object} rule The rule
   * @returns The Turndown instance for chaining
   * @type Object
   */
  addRule: function(key, rule) {
    this.rules.add(key, rule);
    return this;
  },
  /**
   * Keep a node (as HTML) that matches the filter
   * @public
   * @param {String|Array|Function} filter The unique key of the rule
   * @returns The Turndown instance for chaining
   * @type Object
   */
  keep: function(filter) {
    this.rules.keep(filter);
    return this;
  },
  /**
   * Remove a node that matches the filter
   * @public
   * @param {String|Array|Function} filter The unique key of the rule
   * @returns The Turndown instance for chaining
   * @type Object
   */
  remove: function(filter) {
    this.rules.remove(filter);
    return this;
  },
  /**
   * Escapes Markdown syntax
   * @public
   * @param {String} string The string to escape
   * @returns A string with Markdown syntax escaped
   * @type String
   */
  escape: function(string) {
    return escapes.reduce(function(accumulator, escape) {
      return accumulator.replace(escape[0], escape[1]);
    }, string);
  }
};
function process2(parentNode) {
  var self = this;
  return reduce.call(parentNode.childNodes, function(output, node) {
    node = new Node(node, self.options);
    var replacement = "";
    if (node.nodeType === 3) {
      replacement = node.isCode ? node.nodeValue : self.escape(node.nodeValue);
    } else if (node.nodeType === 1) {
      replacement = replacementForNode.call(self, node);
    }
    return join2(output, replacement);
  }, "");
}
function postProcess(output) {
  var self = this;
  this.rules.forEach(function(rule) {
    if (typeof rule.append === "function") {
      output = join2(output, rule.append(self.options));
    }
  });
  return output.replace(/^[\t\r\n]+/, "").replace(/[\t\r\n\s]+$/, "");
}
function replacementForNode(node) {
  var rule = this.rules.forNode(node);
  var content = process2.call(this, node);
  var whitespace = node.flankingWhitespace;
  if (whitespace.leading || whitespace.trailing)
    content = content.trim();
  return whitespace.leading + rule.replacement(content, node, this.options) + whitespace.trailing;
}
function join2(output, replacement) {
  var s1 = trimTrailingNewlines(output);
  var s2 = trimLeadingNewlines(replacement);
  var nls = Math.max(output.length - s1.length, replacement.length - s2.length);
  var separator = "\n\n".substring(0, nls);
  return s1 + separator + s2;
}
function canConvert(input) {
  return input != null && (typeof input === "string" || input.nodeType && (input.nodeType === 1 || input.nodeType === 9 || input.nodeType === 11));
}
var turndown_browser_es_default = TurndownService;

// src/convert/turndown.ts
function createTurndownService() {
  const turndown2 = new turndown_browser_es_default({
    headingStyle: "atx",
    codeBlockStyle: "fenced"
  });
  turndown2.remove(["style", "script", "meta", "link"]);
  turndown2.addRule("googleDocsListItem", {
    filter: "li",
    replacement(content, node, options) {
      var _a, _b, _c, _d;
      const parentClass = (_c = (_b = (_a = node.parentNode) == null ? void 0 : _a.getAttribute) == null ? void 0 : _b.call(_a, "class")) != null ? _c : "";
      const depthMatch = parentClass.match(/lst-kix_[a-z0-9]+-(\d+)/);
      const depth = depthMatch ? parseInt(depthMatch[1], 10) : 0;
      const indent = "    ".repeat(depth);
      content = content.replace(/^\n+/, "").replace(/\n+$/, "\n").replace(/\n/gm, "\n" + indent + "    ");
      let prefix;
      const parent = node.parentNode;
      if ((parent == null ? void 0 : parent.nodeName) === "OL") {
        const start = (_d = parent.getAttribute) == null ? void 0 : _d.call(parent, "start");
        const index = Array.prototype.indexOf.call(parent.children, node);
        prefix = (start ? Number(start) + index : index + 1) + ". ";
      } else {
        prefix = options.bulletListMarker + " ";
      }
      return indent + prefix + content + (node.nextSibling && !/\n$/.test(content) ? "\n" : "");
    }
  });
  return turndown2;
}

// src/convert/format.ts
var OFFICE_DOC_MIMES = /* @__PURE__ */ new Set([
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "application/msword"
]);
var OFFICE_SHEET_MIMES = /* @__PURE__ */ new Set([
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  "application/vnd.ms-excel"
]);
var OFFICE_SLIDES_MIMES = /* @__PURE__ */ new Set([
  "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  "application/vnd.ms-powerpoint"
]);
function getFormatMapping(file) {
  const mime = file.MimeType;
  const isVirtual = file.Size === -1;
  if (mime === "application/vnd.google-apps.document") {
    return { exportFormat: "html", extension: ".md", convert: "turndown", addFrontmatter: true };
  }
  if (mime === "application/vnd.google-apps.spreadsheet") {
    return { exportFormat: "csv", extension: ".csv", convert: "passthrough", addFrontmatter: false };
  }
  if (mime === "application/vnd.google-apps.presentation") {
    return { exportFormat: "txt", extension: ".md", convert: "passthrough", addFrontmatter: true };
  }
  if (isVirtual && OFFICE_DOC_MIMES.has(mime)) {
    return { exportFormat: "html", extension: ".md", convert: "turndown", addFrontmatter: true };
  }
  if (isVirtual && OFFICE_SHEET_MIMES.has(mime)) {
    return { exportFormat: "csv", extension: ".csv", convert: "passthrough", addFrontmatter: false };
  }
  if (isVirtual && OFFICE_SLIDES_MIMES.has(mime)) {
    return { exportFormat: "txt", extension: ".md", convert: "passthrough", addFrontmatter: true };
  }
  const dotIdx = file.Name.lastIndexOf(".");
  const ext = dotIdx > 0 ? file.Name.substring(dotIdx) : "";
  return { exportFormat: void 0, extension: ext, convert: "passthrough", addFrontmatter: false };
}
function stripVirtualExt(name) {
  return name.replace(/\.(gdoc|gsheet|gslides|gform)$/, "");
}
function sanitizeFilename(name) {
  let s = name.replace(/[<>:"|?*\\]/g, "_").replace(/[#^\[\]]/g, "").replace(/^\./, "_").trim();
  return s || "_";
}
function toVaultPath(file, vaultRoot) {
  const mapping = getFormatMapping(file);
  const stripped = stripVirtualExt(file.Name);
  let baseName;
  if (mapping.exportFormat) {
    const dotIdx = stripped.lastIndexOf(".");
    const nameWithoutExt = dotIdx > 0 ? stripped.substring(0, dotIdx) : stripped;
    baseName = `${nameWithoutExt}${mapping.extension}`;
  } else if (stripped !== file.Name) {
    baseName = `${stripped}${mapping.extension}`;
  } else {
    baseName = stripped;
  }
  const fileName = sanitizeFilename(baseName);
  const dirParts = file.Path.split("/");
  dirParts.pop();
  const sanitizedDirs = dirParts.filter((p) => p.length > 0).map(sanitizeFilename);
  const dir = sanitizedDirs.length > 0 ? sanitizedDirs.join("/") : "";
  const fullDir = dir ? `${vaultRoot}/${dir}` : vaultRoot;
  return `${fullDir}/${fileName}`;
}
function driveEditUrl(file) {
  const mime = file.MimeType;
  if (mime === "application/vnd.google-apps.document" || OFFICE_DOC_MIMES.has(mime)) {
    return `https://docs.google.com/document/d/${file.ID}`;
  }
  if (mime === "application/vnd.google-apps.spreadsheet" || OFFICE_SHEET_MIMES.has(mime)) {
    return `https://docs.google.com/spreadsheets/d/${file.ID}`;
  }
  if (mime === "application/vnd.google-apps.presentation" || OFFICE_SLIDES_MIMES.has(mime)) {
    return `https://docs.google.com/presentation/d/${file.ID}`;
  }
  return void 0;
}

// src/convert/index.ts
var TAG2 = "[G Command]";
var turndown = createTurndownService();
function formatSyncDate(d) {
  const pad = (n) => String(n).padStart(2, "0");
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`;
}
function buildFrontmatter(file, includeGdriveFields = true) {
  const now = formatSyncDate(/* @__PURE__ */ new Date());
  const lines = ["---"];
  if (includeGdriveFields) {
    lines.push(`gdrive_id: "${file.ID}"`);
    lines.push(`gdrive_path: "${file.Path}"`);
    const url = driveEditUrl(file);
    if (url) {
      lines.push(`google_document: "${url}"`);
    }
  }
  lines.push(`synced: "${now}"`);
  lines.push("---", "");
  return lines.join("\n");
}
function convertContent(raw, mapping, file, includeGdriveFields = true) {
  var _a, _b, _c, _d, _e, _f;
  let content;
  if (mapping.convert === "turndown") {
    const liSample = (_b = (_a = raw.match(/<li[^>]*>.*?<\/li>/gs)) == null ? void 0 : _a.slice(0, 3)) != null ? _b : [];
    const olSample = (_d = (_c = raw.match(/<ol[^>]*>/g)) == null ? void 0 : _c.slice(0, 3)) != null ? _d : [];
    const ulSample = (_f = (_e = raw.match(/<ul[^>]*>/g)) == null ? void 0 : _e.slice(0, 3)) != null ? _f : [];
    console.log(TAG2, `List diagnostics: ${liSample.length > 0 ? "found <li>" : "no <li>"}`);
    for (const s of liSample)
      console.log(TAG2, `  <li> sample: ${s.substring(0, 200)}`);
    for (const s of olSample)
      console.log(TAG2, `  <ol> sample: ${s}`);
    for (const s of ulSample)
      console.log(TAG2, `  <ul> sample: ${s}`);
    content = turndown.turndown(raw);
  } else {
    content = raw;
  }
  if (mapping.addFrontmatter) {
    content = buildFrontmatter(file, includeGdriveFields) + content;
  }
  return content;
}

// src/SyncManager.ts
var TAG3 = "[G Command]";
var noop = () => {
};
async function syncFiles(files, app, drive, settings, saveSettings, onLog = noop) {
  var _a;
  const result = { synced: 0, skipped: 0, failed: [] };
  for (const file of files) {
    if (file.IsDir)
      continue;
    try {
      const existing = settings.syncState[file.Path];
      if (existing && existing.modTime === file.ModTime) {
        result.skipped++;
        continue;
      }
      const mapping = getFormatMapping(file);
      const detail = `mime=${file.MimeType}, size=${file.Size}, export=${(_a = mapping.exportFormat) != null ? _a : "native"}, convert=${mapping.convert}, ext=${mapping.extension}`;
      onLog("info", `${file.Name} \u2014 ${detail}`);
      console.log(TAG3, `Sync: ${file.Path} (${detail})`);
      const raw = await drive.download(file.Path, mapping.exportFormat);
      console.log(TAG3, `Raw content: length=${raw.length}, convert=${mapping.convert}, first200="${raw.substring(0, 200).replace(/\n/g, "\\n")}"`);
      let content;
      try {
        content = convertContent(raw, mapping, file, settings.frontmatterGdriveFields);
      } catch (convErr) {
        const msg = convErr instanceof Error ? convErr.message : String(convErr);
        console.error(TAG3, `Conversion failed for ${file.Path}: ${msg}`);
        console.error(TAG3, `Raw content that failed conversion (first 500 chars):`, raw.substring(0, 500));
        throw new Error(`Conversion failed (${mapping.convert}): ${msg}`);
      }
      console.log(TAG3, `Converted content: length=${content.length}, first200="${content.substring(0, 200).replace(/\n/g, "\\n")}"`);
      const vaultPath = toVaultPath(file, settings.vaultRoot);
      await writeToVault(app, vaultPath, content);
      settings.syncState[file.Path] = {
        modTime: file.ModTime,
        vaultPath,
        fileId: file.ID,
        mimeType: file.MimeType
      };
      await saveSettings();
      result.synced++;
      onLog("info", `\u2713 ${file.Name} \u2192 ${vaultPath}`);
      console.log(TAG3, `Synced: ${file.Path} \u2192 ${vaultPath}`);
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      console.error(TAG3, `Failed to sync ${file.Path}:`, msg);
      console.error(TAG3, `File metadata:`, JSON.stringify(file, null, 2));
      onLog("error", `\u2717 ${file.Name}: ${msg}`);
      result.failed.push(file.Path);
    }
  }
  return result;
}
async function writeToVault(app, path, content) {
  const parts = path.split("/");
  parts.pop();
  if (parts.length > 0) {
    let current = "";
    for (const seg of parts) {
      current = current ? `${current}/${seg}` : seg;
      if (!app.vault.getAbstractFileByPath(current)) {
        await app.vault.createFolder(current);
      }
    }
  }
  const existing = app.vault.getAbstractFileByPath(path);
  if (existing && existing instanceof import_obsidian.TFile) {
    await app.vault.modify(existing, content);
  } else {
    await app.vault.create(path, content);
  }
}

// src/GDriveSidebar.ts
var VIEW_TYPE_GDRIVE_SIDEBAR = "warped-reference-drive";
var KEBAB_SVG = '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="5" r="1"></circle><circle cx="12" cy="12" r="1"></circle><circle cx="12" cy="19" r="1"></circle></svg>';
var MAX_LOG_ENTRIES = 50;
var GDriveSidebar = class extends import_obsidian2.ItemView {
  constructor(leaf, app, drive, settings, saveSettings, onOpenSettings, pluginDir) {
    super(leaf);
    this.rootNodes = null;
    this.error = null;
    this.loadingRoot = false;
    this.searchQuery = "";
    this.allFiles = null;
    // cached recursive results
    this.searchingAll = false;
    this.syncing = false;
    this.syncStatus = "idle";
    this.logEntries = [];
    this.logCollapsed = true;
    this.connectingInProgress = false;
    this.appRef = app;
    this.drive = drive;
    this.settings = settings;
    this.saveSettings = saveSettings;
    this.selectedPaths = new Set(settings.selectedPaths);
    this.onOpenSettings = onOpenSettings;
    this.pluginDir = pluginDir;
  }
  getViewType() {
    return VIEW_TYPE_GDRIVE_SIDEBAR;
  }
  getDisplayText() {
    return "Google Drive";
  }
  getIcon() {
    return "hard-drive";
  }
  async onOpen() {
    const cache = this.settings.driveCache;
    if (cache && cache.folders[""]) {
      this.rootNodes = buildTreeFromCache(cache);
      this.render();
      this.backgroundRefresh();
    } else {
      await this.loadRoot();
    }
  }
  onClose() {
    this.rootNodes = null;
    this.allFiles = null;
    this.searchQuery = "";
    return Promise.resolve();
  }
  // --- Public API -----------------------------------------------------------
  /** Full data reload: re-checks rclone and reloads the Drive root. */
  async reload() {
    await this.loadRoot();
  }
  /** Sync selected files to the vault. */
  async syncSelected() {
    if (this.selectedPaths.size === 0 || this.syncing)
      return;
    const files = await this.collectSelectedFiles();
    if (files.length === 0)
      return;
    await this.runSync(files);
  }
  /** Resync all previously synced files. */
  async resyncAll() {
    if (this.syncing)
      return;
    const paths = Object.keys(this.settings.syncState);
    if (paths.length === 0)
      return;
    const files = this.collectSyncedFiles(paths);
    if (files.length === 0)
      return;
    await this.runSync(files);
  }
  async runSync(files) {
    this.syncing = true;
    this.syncStatus = "syncing";
    this.log("info", `Syncing ${files.length} file(s)\u2026`);
    this.render();
    const onLog = (level, msg) => {
      this.log(level, msg);
      this.render();
    };
    try {
      const result = await syncFiles(
        files,
        this.appRef,
        this.drive,
        this.settings,
        this.saveSettings,
        onLog
      );
      const parts = [];
      if (result.synced > 0)
        parts.push(`${result.synced} synced`);
      if (result.skipped > 0)
        parts.push(`${result.skipped} unchanged`);
      if (result.failed.length > 0)
        parts.push(`${result.failed.length} failed`);
      this.log("info", `Done: ${parts.join(", ")}`);
      this.syncStatus = result.failed.length > 0 ? "error" : "idle";
      if (result.synced > 0 && this.settings.driveCache) {
        this.prefetchSyncedParents();
      }
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      this.log("error", `Sync error: ${msg}`);
      this.syncStatus = "error";
    } finally {
      this.syncing = false;
      this.render();
    }
  }
  /** Collect DriveFile objects for all selected paths from the loaded tree. */
  async collectSelectedFiles() {
    const seen = /* @__PURE__ */ new Set();
    const files = [];
    const addFile = (f) => {
      if (!f.IsDir && !seen.has(f.Path)) {
        seen.add(f.Path);
        files.push(f);
      }
    };
    const collect = (nodes) => {
      if (!nodes)
        return;
      for (const node of nodes) {
        if (!node.file.IsDir && this.selectedPaths.has(node.file.Path)) {
          addFile(node.file);
        }
        if (node.children)
          collect(node.children);
      }
    };
    collect(this.rootNodes);
    if (this.allFiles) {
      for (const f of this.allFiles) {
        if (this.selectedPaths.has(f.Path))
          addFile(f);
      }
    }
    const folderPaths = this.findSelectedFolders();
    for (const folderPath of folderPaths) {
      try {
        const children = await this.drive.listRecursive(folderPath);
        for (const f of children) {
          f.Path = `${folderPath}/${f.Path}`;
          addFile(f);
        }
      } catch (e) {
        const msg = e instanceof Error ? e.message : String(e);
        this.log("error", `Failed to list folder ${folderPath}: ${msg}`);
      }
    }
    return files;
  }
  /** Find selected paths that are known folder nodes in the loaded tree. */
  findSelectedFolders() {
    const folders = [];
    const walk = (nodes) => {
      if (!nodes)
        return;
      for (const node of nodes) {
        if (node.file.IsDir && this.selectedPaths.has(node.file.Path)) {
          folders.push(node.file.Path);
        }
        if (node.children)
          walk(node.children);
      }
    };
    walk(this.rootNodes);
    return folders;
  }
  /** Build DriveFile list for resync from syncState paths, using loaded tree data. */
  collectSyncedFiles(paths) {
    var _a;
    const fileMap = /* @__PURE__ */ new Map();
    const index = (nodes) => {
      if (!nodes)
        return;
      for (const node of nodes) {
        if (!node.file.IsDir)
          fileMap.set(node.file.Path, node.file);
        if (node.children)
          index(node.children);
      }
    };
    index(this.rootNodes);
    if (this.allFiles) {
      for (const f of this.allFiles) {
        if (!f.IsDir)
          fileMap.set(f.Path, f);
      }
    }
    const files = [];
    for (const p of paths) {
      const f = fileMap.get(p);
      if (f) {
        files.push(f);
      } else {
        const rec = this.settings.syncState[p];
        if (rec) {
          const name = (_a = p.split("/").pop()) != null ? _a : p;
          files.push({
            Path: p,
            Name: name,
            Size: -1,
            MimeType: "",
            // syncFiles uses getFormatMapping which handles unknown mimes
            ModTime: "",
            // empty forces re-download (won't match stored modTime)
            IsDir: false,
            ID: rec.fileId
          });
        }
      }
    }
    return files;
  }
  persistSelectedPaths() {
    this.settings.selectedPaths = Array.from(this.selectedPaths);
    this.saveSettings();
  }
  log(level, message) {
    const now = /* @__PURE__ */ new Date();
    const time = now.toTimeString().slice(0, 8);
    this.logEntries.push({ time, level, message });
    if (this.logEntries.length > MAX_LOG_ENTRIES) {
      this.logEntries.shift();
    }
    if (level === "error") {
      console.error("[G Command]", message);
    } else {
      console.log("[G Command]", message);
    }
  }
  render() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("warped-reference-sidebar");
    this.renderHeader(container);
    this.renderSearchBar(container);
    this.renderStatusLine(container);
    if (this.error) {
      this.renderErrorBanner(container);
      return;
    }
    if (Object.keys(this.settings.syncState).length > 0) {
      this.renderSyncedPane(container);
    }
    container.createDiv({ cls: "warped-reference-section-header", text: "Drive" });
    const tree = container.createDiv({ cls: "warped-reference-tree" });
    if (this.loadingRoot) {
      tree.createDiv({ cls: "warped-reference-loading", text: "Loading\u2026" });
      return;
    }
    if (!this.rootNodes || this.rootNodes.length === 0) {
      tree.createDiv({ cls: "warped-reference-empty", text: "No files found" });
      return;
    }
    const query = this.searchQuery.trim();
    let displayNodes;
    if (query) {
      if (this.allFiles) {
        const allNodes = flattenToNodes(this.allFiles);
        displayNodes = filterTree(allNodes, query);
      } else {
        displayNodes = filterTree(this.rootNodes, query);
      }
    } else {
      displayNodes = this.rootNodes;
    }
    if (query && displayNodes.length === 0 && !this.allFiles) {
      tree.createDiv({ cls: "warped-reference-empty", text: "No matches in loaded folders" });
    } else if (query && displayNodes.length === 0) {
      tree.createDiv({ cls: "warped-reference-empty", text: "No matches found" });
    } else {
      for (const node of displayNodes) {
        this.renderNode(tree, node, 0);
      }
    }
    if (query && !this.allFiles) {
      this.renderSearchAllButton(tree);
    }
    if (this.logEntries.length > 0) {
      this.renderLogPane(container);
    }
  }
  // --- Data loading ---------------------------------------------------------
  async loadRoot() {
    this.loadingRoot = true;
    this.error = null;
    this.allFiles = null;
    this.render();
    try {
      await this.drive.check();
      const files = await this.drive.list("");
      this.rootNodes = files.sort(sortDirsFirst).map(toTreeNode);
      this.ensureCache();
      this.settings.driveCache.folders[""] = files;
      this.settings.driveCache.lastRefresh = (/* @__PURE__ */ new Date()).toISOString();
      await this.saveSettings();
    } catch (e) {
      const err2 = e instanceof DriveError || e instanceof Error ? e : new Error(String(e));
      console.error("[G Command] loadRoot failed:", err2.message);
      this.error = err2;
      this.rootNodes = null;
    } finally {
      this.loadingRoot = false;
      this.render();
    }
  }
  async loadChildren(node) {
    var _a;
    const path = node.file.Path;
    const cached = (_a = this.settings.driveCache) == null ? void 0 : _a.folders[path];
    if (cached) {
      const files = cached.map((f) => ({ ...f, Path: `${path}/${f.Path}` }));
      node.children = files.sort(sortDirsFirst).map(toTreeNode);
      this.backgroundRefreshFolder(node);
      return;
    }
    try {
      const files = await this.drive.list(path);
      this.saveFolderToCache(path, files.map((f) => ({ ...f })));
      for (const f of files) {
        f.Path = `${path}/${f.Path}`;
      }
      node.children = files.sort(sortDirsFirst).map(toTreeNode);
    } catch (e) {
      const msg = `Failed to load ${node.file.Name}: ${e instanceof Error ? e.message : String(e)}`;
      console.error("[G Command]", msg);
      node.children = [];
      this.error = new Error(msg);
    }
  }
  // --- Caching --------------------------------------------------------------
  /** Ensure driveCache is initialised. */
  ensureCache() {
    if (!this.settings.driveCache) {
      this.settings.driveCache = { lastRefresh: "", folders: {} };
    }
  }
  /** Save a folder listing (with raw relative paths) to cache. */
  saveFolderToCache(path, files) {
    this.ensureCache();
    this.settings.driveCache.folders[path] = files;
    this.saveSettings();
  }
  /** Background refresh: fetch fresh root listing and update cache if changed. */
  async backgroundRefresh() {
    try {
      await this.drive.check();
      const freshRoot = await this.drive.list("");
      const cache = this.settings.driveCache;
      const cachedRoot = cache == null ? void 0 : cache.folders[""];
      const changed = !cachedRoot || JSON.stringify(freshRoot) !== JSON.stringify(cachedRoot);
      if (changed) {
        this.ensureCache();
        this.settings.driveCache.folders[""] = freshRoot;
        this.rootNodes = buildTreeFromCache(this.settings.driveCache);
        this.render();
        console.log("[G Command] Background refresh: root updated");
      } else {
        console.log("[G Command] Background refresh: root unchanged");
      }
      await this.prefetchSyncedParents();
      this.settings.driveCache.lastRefresh = (/* @__PURE__ */ new Date()).toISOString();
      await this.saveSettings();
    } catch (e) {
      console.error("[G Command] Background refresh failed:", e instanceof Error ? e.message : String(e));
    }
  }
  /** Background refresh a single folder node. */
  async backgroundRefreshFolder(node) {
    var _a;
    const path = node.file.Path;
    try {
      const freshFiles = await this.drive.list(path);
      const cached = (_a = this.settings.driveCache) == null ? void 0 : _a.folders[path];
      if (!cached || JSON.stringify(freshFiles) !== JSON.stringify(cached)) {
        this.saveFolderToCache(path, freshFiles.map((f) => ({ ...f })));
        const files = freshFiles.map((f) => ({ ...f, Path: `${path}/${f.Path}` }));
        node.children = files.sort(sortDirsFirst).map(toTreeNode);
        this.render();
      }
    } catch (e) {
    }
  }
  /** Pre-fetch parent folders of all synced files so their paths are visible. */
  async prefetchSyncedParents() {
    const parentPaths = syncedParentPaths(this.settings.syncState);
    const cache = this.settings.driveCache;
    for (const parentPath of parentPaths) {
      if (cache.folders[parentPath])
        continue;
      try {
        const files = await this.drive.list(parentPath);
        cache.folders[parentPath] = files;
      } catch (e) {
      }
    }
  }
  // --- Rendering helpers ----------------------------------------------------
  renderHeader(parent) {
    const header = parent.createDiv({ cls: "warped-reference-header" });
    const titleEl = header.createEl("div", { cls: "warped-reference-header-title" });
    titleEl.createEl("span", { cls: "warped-reference-logo", text: "GC" });
    titleEl.createEl("h4", { text: "Drive" });
    const buttonGroup = header.createEl("div", { cls: "warped-reference-button-group" });
    const hasSelection = this.selectedPaths.size > 0;
    const syncBtn = buttonGroup.createEl("button", {
      cls: "warped-reference-sync-btn clickable-icon",
      attr: { "aria-label": hasSelection ? `Sync ${this.selectedPaths.size} file(s)` : "Select files to sync" }
    });
    syncBtn.createSpan({ text: this.syncing ? "\u23F3" : "\u21BB" });
    syncBtn.disabled = !hasSelection || this.syncing;
    syncBtn.addEventListener("click", () => this.syncSelected());
    const menuBtn = buttonGroup.createEl("button", {
      cls: "clickable-icon warped-reference-menu-btn",
      attr: { "aria-label": "Menu" }
    });
    menuBtn.innerHTML = KEBAB_SVG;
    const hasSyncedFiles = Object.keys(this.settings.syncState).length > 0;
    menuBtn.addEventListener("click", (evt) => {
      const menu = new import_obsidian2.Menu();
      menu.addItem(
        (item) => item.setTitle("Refresh drive contents").setIcon("refresh-cw").onClick(() => {
          this.settings.driveCache = null;
          this.loadRoot();
        })
      );
      if (hasSyncedFiles) {
        menu.addItem(
          (item) => item.setTitle("Resync files").setIcon("refresh-cw").onClick(() => this.resyncAll())
        );
        menu.addItem(
          (item) => item.setTitle("Clear history").setIcon("trash").onClick(async () => {
            this.settings.syncState = {};
            await this.saveSettings();
            this.log("info", "Sync cache cleared \u2014 all files will re-download on next sync");
            this.render();
          })
        );
      }
      menu.addSeparator();
      menu.addItem(
        (item) => item.setTitle("Settings").setIcon("settings").onClick(() => this.onOpenSettings())
      );
      menu.showAtMouseEvent(evt);
    });
  }
  renderSearchBar(parent) {
    const row = parent.createDiv({ cls: "warped-reference-search-row" });
    const input = row.createEl("input", {
      cls: "warped-reference-search",
      attr: { type: "text", placeholder: "Search files\u2026" }
    });
    input.value = this.searchQuery;
    input.addEventListener("input", () => {
      this.searchQuery = input.value;
      this.render();
    });
    requestAnimationFrame(() => {
      if (this.searchQuery) {
        input.focus();
        input.selectionStart = input.selectionEnd = input.value.length;
      }
    });
    if (this.searchQuery) {
      const clearBtn = row.createEl("button", {
        cls: "warped-reference-search-clear clickable-icon",
        attr: { "aria-label": "Clear search" }
      });
      clearBtn.textContent = "\u2715";
      clearBtn.addEventListener("click", () => {
        this.searchQuery = "";
        this.allFiles = null;
        this.render();
      });
    }
  }
  renderSearchAllButton(parent) {
    const btn = parent.createEl("button", {
      cls: "warped-reference-search-all-btn",
      text: this.searchingAll ? "Searching\u2026" : "Search all of Drive"
    });
    btn.disabled = this.searchingAll;
    btn.addEventListener("click", async () => {
      this.searchingAll = true;
      this.render();
      try {
        this.allFiles = await this.drive.listRecursive("");
        console.log("[G Command] Search all: loaded", this.allFiles.length, "files");
      } catch (e) {
        const msg = e instanceof Error ? e.message : String(e);
        console.error("[G Command] Search all failed:", msg);
        this.error = new Error(`Search failed: ${msg}`);
      } finally {
        this.searchingAll = false;
        this.render();
      }
    });
  }
  renderStatusLine(parent) {
    const text = this.syncing ? "Syncing\u2026" : "Read only access to Google Drive documents, in Markdown or CSV.";
    parent.createDiv({ cls: "warped-reference-status", text });
  }
  renderSyncedPane(parent) {
    const pane = parent.createDiv({ cls: "warped-reference-synced-pane" });
    const entries = Object.entries(this.settings.syncState);
    pane.createDiv({
      cls: "warped-reference-section-header",
      text: `Synced files (${entries.length})`
    });
    const body = pane.createDiv({ cls: "warped-reference-synced-body" });
    for (const [drivePath, rec] of entries) {
      this.renderSyncedRow(body, drivePath, rec);
    }
  }
  renderSyncedRow(parent, drivePath, rec) {
    var _a, _b;
    const row = parent.createDiv({ cls: "warped-reference-synced-row" });
    const displayName = (_b = ((_a = rec.vaultPath) != null ? _a : drivePath).split("/").pop()) != null ? _b : drivePath;
    row.createSpan({ cls: "warped-reference-synced-name", text: displayName });
    const btn = row.createEl("button", {
      cls: "warped-reference-resync-btn clickable-icon",
      attr: { "aria-label": `Resync ${displayName}` }
    });
    btn.textContent = "\u21BB";
    btn.addEventListener("click", (e) => {
      var _a2, _b2;
      e.stopPropagation();
      const name = (_a2 = drivePath.split("/").pop()) != null ? _a2 : drivePath;
      const stub = {
        Path: drivePath,
        Name: name,
        Size: -1,
        MimeType: (_b2 = rec.mimeType) != null ? _b2 : "",
        ModTime: "",
        IsDir: false,
        ID: rec.fileId
      };
      this.runSync([stub]);
    });
  }
  renderLogPane(parent) {
    const pane = parent.createDiv({ cls: "warped-reference-log-pane" });
    const header = pane.createDiv({ cls: "warped-reference-log-header" });
    const arrow = header.createSpan({ cls: "warped-reference-log-arrow", text: this.logCollapsed ? "\u25B6" : "\u25BC" });
    header.createDiv({ cls: `warped-reference-log-status warped-reference-log-status--${this.syncStatus}` });
    header.createSpan({ text: `Sync log (${this.logEntries.length})` });
    const clearBtn = header.createEl("button", {
      cls: "warped-reference-log-clear clickable-icon",
      attr: { "aria-label": "Clear log" }
    });
    clearBtn.textContent = "\u2715";
    clearBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      this.logEntries = [];
      this.syncStatus = "idle";
      this.render();
    });
    header.addEventListener("click", () => {
      this.logCollapsed = !this.logCollapsed;
      this.render();
    });
    if (!this.logCollapsed) {
      const body = pane.createDiv({ cls: "warped-reference-log-body" });
      for (const entry of this.logEntries) {
        const row = body.createDiv({
          cls: `warped-reference-log-entry ${entry.level === "error" ? "warped-reference-log-entry--error" : ""}`
        });
        row.createSpan({ cls: "warped-reference-log-time", text: entry.time });
        row.createSpan({ text: entry.message });
      }
      requestAnimationFrame(() => {
        body.scrollTop = body.scrollHeight;
      });
    }
  }
  renderErrorBanner(parent) {
    const err2 = this.error;
    const banner = parent.createDiv({ cls: "warped-reference-error-banner" });
    if (err2 instanceof DriveError) {
      if (err2.code === "binary-missing") {
        this.renderBinaryMissing(banner);
      } else {
        this.renderRemoteSetup(banner);
      }
    } else {
      banner.createDiv({ cls: "warped-reference-error-title", text: err2.message });
    }
  }
  renderBinaryMissing(banner) {
    banner.createDiv({ cls: "warped-reference-error-title", text: "rclone is required" });
    banner.createEl("p", { text: "Install rclone to connect to Google Drive:" });
    const info = getRcloneInstallInstructions();
    const codeWrap = banner.createDiv({ cls: "warped-reference-code-block" });
    const pre = codeWrap.createEl("pre");
    pre.createEl("code", { text: info.command });
    const copyBtn = codeWrap.createEl("button", {
      cls: "warped-reference-copy-btn clickable-icon",
      attr: { "aria-label": "Copy to clipboard" }
    });
    copyBtn.textContent = "Copy";
    copyBtn.addEventListener("click", () => {
      navigator.clipboard.writeText(info.command);
      copyBtn.textContent = "Copied";
      setTimeout(() => copyBtn.textContent = "Copy", 1500);
    });
    const linkP = banner.createEl("p", { cls: "warped-reference-error-ref" });
    linkP.appendText("Other platforms: ");
    const link = linkP.createEl("a", { text: "rclone.org/install", href: "https://rclone.org/install/" });
    link.setAttr("target", "_blank");
    const checkBtn = banner.createEl("button", {
      cls: "mod-cta",
      text: "Check again"
    });
    checkBtn.addEventListener("click", () => this.loadRoot());
  }
  renderRemoteSetup(banner) {
    banner.createDiv({ cls: "warped-reference-error-title", text: "Connect to Google Drive" });
    if (this.connectingInProgress) {
      banner.createEl("p", { text: "Waiting for Google sign-in..." });
      banner.createEl("p", { cls: "warped-reference-error-ref", text: "Complete the sign-in in your browser window." });
      return;
    }
    banner.createEl("p", { text: "Click Connect to sign in with your Google account." });
    const connectBtn = banner.createEl("button", {
      cls: "mod-cta",
      text: "Connect"
    });
    connectBtn.addEventListener("click", () => this.handleConnect());
  }
  async handleConnect() {
    if (this.connectingInProgress)
      return;
    this.connectingInProgress = true;
    this.render();
    const result = await this.drive.setupRemote();
    this.connectingInProgress = false;
    if (result.ok) {
      await this.loadRoot();
    } else {
      this.error = new DriveError(
        result.code === "binary-missing" ? "binary-missing" : "remote-unreachable",
        result.message
      );
      this.render();
    }
  }
  renderNode(parent, node, depth) {
    const row = parent.createDiv({ cls: "warped-reference-row" });
    row.style.paddingLeft = `${12 + depth * 18}px`;
    if (node.file.IsDir) {
      this.renderFolderRow(row, node, depth);
    } else {
      this.renderFileRow(row, node);
    }
  }
  renderFolderRow(row, node, depth) {
    const cb = row.createEl("input", {
      cls: "warped-reference-checkbox",
      attr: { type: "checkbox" }
    });
    cb.checked = this.selectedPaths.has(node.file.Path);
    cb.addEventListener("change", (e) => {
      e.stopPropagation();
      if (cb.checked)
        this.selectedPaths.add(node.file.Path);
      else
        this.selectedPaths.delete(node.file.Path);
      this.persistSelectedPaths();
      this.render();
    });
    const arrow = row.createSpan({ cls: "warped-reference-arrow" });
    arrow.textContent = node.expanded ? "\u25BC" : "\u25B6";
    row.createSpan({ cls: "warped-reference-name", text: sanitizeFilename(node.file.Name) });
    row.addClass("warped-reference-row--folder");
    row.addEventListener("click", async (e) => {
      if (e.target.tagName === "INPUT")
        return;
      if (node.expanded) {
        node.expanded = false;
        this.render();
        return;
      }
      if (node.children === null) {
        arrow.textContent = "";
        arrow.addClass("warped-reference-arrow--loading");
        await this.loadChildren(node);
        arrow.removeClass("warped-reference-arrow--loading");
      }
      node.expanded = true;
      this.render();
    });
    if (node.expanded && node.children) {
      for (const child of node.children) {
        this.renderNode(row.parentElement, child, depth + 1);
      }
    }
  }
  renderFileRow(row, node) {
    const cb = row.createEl("input", {
      cls: "warped-reference-checkbox",
      attr: { type: "checkbox" }
    });
    cb.checked = this.selectedPaths.has(node.file.Path);
    cb.addEventListener("change", () => {
      if (cb.checked) {
        this.selectedPaths.add(node.file.Path);
      } else {
        this.selectedPaths.delete(node.file.Path);
      }
      this.persistSelectedPaths();
      this.render();
    });
    row.createSpan({ cls: "warped-reference-name", text: sanitizeFilename(node.file.Name) });
    if (this.settings.syncState[node.file.Path]) {
      row.createSpan({ cls: "warped-reference-sync-badge", text: "\u2713" });
    }
    row.addClass("warped-reference-row--file");
  }
};
function toTreeNode(file) {
  return { file, children: file.IsDir ? null : [], expanded: false };
}
function sortDirsFirst(a, b) {
  if (a.IsDir !== b.IsDir)
    return a.IsDir ? -1 : 1;
  return a.Name.localeCompare(b.Name);
}
function filterTree(nodes, query) {
  const lq = query.toLowerCase();
  const result = [];
  for (const node of nodes) {
    const nameMatch = node.file.Name.toLowerCase().includes(lq);
    if (node.file.IsDir && node.children && node.children.length > 0) {
      const filteredChildren = filterTree(node.children, query);
      if (nameMatch || filteredChildren.length > 0) {
        result.push({
          file: node.file,
          children: filteredChildren.length > 0 ? filteredChildren : node.children,
          expanded: nameMatch || filteredChildren.length > 0
        });
      }
    } else if (nameMatch) {
      result.push(node);
    }
  }
  return result;
}
function flattenToNodes(files) {
  return files.sort(sortDirsFirst).map(toTreeNode);
}
function buildTreeFromCache(cache) {
  const rootFiles = cache.folders[""];
  if (!rootFiles)
    return [];
  const buildNodes = (files, parentPath) => {
    return files.sort(sortDirsFirst).map((f) => {
      const fullPath = parentPath ? `${parentPath}/${f.Path}` : f.Path;
      const fileWithPath = { ...f, Path: fullPath };
      if (f.IsDir) {
        const cachedChildren = cache.folders[fullPath];
        const children = cachedChildren ? buildNodes(cachedChildren, fullPath) : null;
        return { file: fileWithPath, children, expanded: !!cachedChildren };
      }
      return { file: fileWithPath, children: [], expanded: false };
    });
  };
  return buildNodes(rootFiles, "");
}
function syncedParentPaths(syncState) {
  const parents = /* @__PURE__ */ new Set();
  for (const drivePath of Object.keys(syncState)) {
    const lastSlash = drivePath.lastIndexOf("/");
    if (lastSlash > 0) {
      parents.add(drivePath.substring(0, lastSlash));
    }
  }
  return Array.from(parents);
}

// ../shared/ui/Notice.ts
var import_obsidian3 = require("obsidian");

// ../shared/plugin/SidebarManager.ts
var SidebarManager = class {
  constructor(app, viewType) {
    this.app = app;
    this.viewType = viewType;
  }
  /**
   * Activate the sidebar view (create if needed, reveal if exists).
   */
  async activate() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(this.viewType);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      const rightLeaf = workspace.getRightLeaf(false);
      if (rightLeaf) {
        leaf = rightLeaf;
        await leaf.setViewState({
          type: this.viewType,
          active: true
        });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
  /**
   * Toggle the sidebar view (close if open, open if closed).
   */
  async toggle() {
    const { workspace } = this.app;
    const leaves = workspace.getLeavesOfType(this.viewType);
    if (leaves.length > 0) {
      leaves.forEach((leaf) => leaf.detach());
    } else {
      await this.activate();
    }
  }
  /**
   * Refresh all instances of the sidebar view.
   * Calls reload() if available (full data refresh), otherwise render().
   */
  refresh() {
    const { workspace } = this.app;
    const leaves = workspace.getLeavesOfType(this.viewType);
    for (const leaf of leaves) {
      const view = leaf.view;
      if (view && "reload" in view && typeof view.reload === "function") {
        view.reload();
      } else if (view && "render" in view && typeof view.render === "function") {
        view.render();
      }
    }
  }
  /**
   * Get the first leaf of this sidebar type, if any.
   */
  getLeaf() {
    const leaves = this.app.workspace.getLeavesOfType(this.viewType);
    return leaves.length > 0 ? leaves[0] : null;
  }
  /**
   * Get the view instance from the first leaf, if any.
   */
  getView() {
    const leaf = this.getLeaf();
    return leaf ? leaf.view : null;
  }
  /**
   * Execute a callback on each sidebar view instance.
   */
  forEach(callback) {
    const leaves = this.app.workspace.getLeavesOfType(this.viewType);
    for (const leaf of leaves) {
      callback(leaf.view);
    }
  }
};

// ../shared/llm/LLMClient.ts
var import_obsidian4 = require("obsidian");

// main.ts
var GCommandPlugin = class extends import_obsidian5.Plugin {
  async onload() {
    var _a;
    await this.loadSettings();
    this.drive = new DriveProvider(this.settings.rcloneRemote);
    if (this.settings.rclonePath) {
      this.drive.setPath(this.settings.rclonePath);
    }
    this.sidebarManager = new SidebarManager(this.app, VIEW_TYPE_GDRIVE_SIDEBAR);
    const pluginDir = (_a = this.manifest.dir) != null ? _a : "";
    this.registerView(
      VIEW_TYPE_GDRIVE_SIDEBAR,
      (leaf) => new GDriveSidebar(
        leaf,
        this.app,
        this.drive,
        this.settings,
        () => this.saveSettings(),
        () => this.openSettings(),
        pluginDir
      )
    );
    this.app.workspace.onLayoutReady(() => {
      this.sidebarManager.activate();
    });
    this.addCommand({
      id: "open-drive-browser",
      name: "Open Drive browser",
      callback: () => this.sidebarManager.toggle()
    });
    this.addCommand({
      id: "sync-drive-files",
      name: "Sync Drive files",
      callback: () => {
        const view = this.sidebarManager.getView();
        if (view)
          view.resyncAll();
      }
    });
    this.addRibbonIcon("hard-drive", "Google Drive", () => {
      this.sidebarManager.toggle();
    });
    this.addSettingTab(new GCommandSettingTab(this.app, this));
    this.registerEvent(
      this.app.vault.on("delete", (file) => {
        const drivePath = Object.keys(this.settings.syncState).find(
          (k) => this.settings.syncState[k].vaultPath === file.path
        );
        if (!drivePath)
          return;
        delete this.settings.syncState[drivePath];
        const idx = this.settings.selectedPaths.indexOf(drivePath);
        if (idx !== -1)
          this.settings.selectedPaths.splice(idx, 1);
        this.saveSettings();
        this.sidebarManager.refresh();
      })
    );
  }
  onunload() {
  }
  openSettings() {
    const setting = this.app.setting;
    if (setting) {
      setting.open();
      setting.openTabById("warped-reference");
    }
  }
  /** Push remote name change to the provider and reload the sidebar. */
  updateRemote() {
    this.drive.setRemote(this.settings.rcloneRemote);
    this.sidebarManager.refresh();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var GCommandSettingTab = class extends import_obsidian5.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.connectionStatus = "idle";
    this.connectionError = "";
    this.hasChecked = false;
    this.plugin = plugin;
    this.debouncedUpdateRemote = (0, import_obsidian5.debounce)(() => this.plugin.updateRemote(), 500, true);
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    this.renderConnectionStatus(containerEl);
    new import_obsidian5.Setting(containerEl).setName("rclone remote").setDesc("Name of the rclone remote for Google Drive. Default: gdrive.").addText(
      (text) => text.setPlaceholder("gdrive").setValue(this.plugin.settings.rcloneRemote).onChange(async (value) => {
        this.plugin.settings.rcloneRemote = value.trim() || "gdrive";
        await this.plugin.saveSettings();
        this.debouncedUpdateRemote();
        this.connectionStatus = "idle";
        this.hasChecked = false;
      })
    );
    new import_obsidian5.Setting(containerEl).setName("rclone path").setDesc(
      "Absolute path to the rclone binary. Leave empty to auto-detect (Homebrew, /usr/local/bin, PATH)."
    ).addText(
      (text) => text.setPlaceholder("auto-detect").setValue(this.plugin.settings.rclonePath).onChange(async (value) => {
        this.plugin.settings.rclonePath = value.trim();
        await this.plugin.saveSettings();
        this.plugin.drive.setPath(this.plugin.settings.rclonePath);
        this.plugin.sidebarManager.refresh();
        this.connectionStatus = "idle";
        this.hasChecked = false;
      })
    );
    new import_obsidian5.Setting(containerEl).setName("Vault sync root").setDesc(
      "Folder in this vault where synced Drive files will be written. Drive folder structure is mirrored inside it."
    ).addText(
      (text) => text.setPlaceholder("gdrive").setValue(this.plugin.settings.vaultRoot).onChange(async (value) => {
        this.plugin.settings.vaultRoot = value.trim() || "gdrive";
        await this.plugin.saveSettings();
      })
    ).addButton(
      (btn) => btn.setButtonText("Show in Finder").onClick(async () => {
        var _a, _b, _c;
        const adapter = this.app.vault.adapter;
        const basePath = (_b = (_a = adapter.getBasePath) == null ? void 0 : _a.call(adapter)) != null ? _b : "";
        if (!basePath)
          return;
        const syncRoot = this.plugin.settings.vaultRoot;
        if (!this.app.vault.getAbstractFileByPath(syncRoot)) {
          await this.app.vault.createFolder(syncRoot);
        }
        const fullPath = `${basePath}/${syncRoot}`;
        const { shell } = (_c = require("electron").remote) != null ? _c : require("electron");
        shell.showItemInFolder(fullPath);
      })
    );
    new import_obsidian5.Setting(containerEl).setName("Include Drive metadata in frontmatter").setDesc(
      "Add gdrive_id and gdrive_path fields to synced markdown files. The synced timestamp is always included."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.frontmatterGdriveFields).onChange(async (value) => {
        this.plugin.settings.frontmatterGdriveFields = value;
        await this.plugin.saveSettings();
      })
    );
    if (!this.hasChecked) {
      this.checkConnection();
    }
  }
  renderConnectionStatus(containerEl) {
    const setting = new import_obsidian5.Setting(containerEl).setName("Google Drive");
    switch (this.connectionStatus) {
      case "checking": {
        setting.setDesc("Checking connection...");
        setting.addButton((btn) => btn.setButtonText("Checking...").setDisabled(true));
        break;
      }
      case "connected": {
        const descEl = document.createDocumentFragment();
        const dot = document.createElement("span");
        dot.className = "warped-reference-connection-dot warped-reference-connection-dot--connected";
        descEl.appendChild(dot);
        descEl.appendText(" Connected");
        setting.setDesc(descEl);
        break;
      }
      case "connecting": {
        const descEl = document.createDocumentFragment();
        const dot = document.createElement("span");
        dot.className = "warped-reference-connection-dot warped-reference-connection-dot--connecting";
        descEl.appendChild(dot);
        descEl.appendText(" Waiting for Google sign-in... Complete the sign-in in your browser.");
        setting.setDesc(descEl);
        setting.addButton((btn) => btn.setButtonText("Connecting...").setDisabled(true));
        break;
      }
      case "error": {
        setting.setDesc(this.connectionError);
        setting.addButton(
          (btn) => btn.setButtonText("Retry").setCta().onClick(() => this.connectDrive())
        );
        break;
      }
      case "binary-missing": {
        const info = getRcloneInstallInstructions();
        const descEl = document.createDocumentFragment();
        descEl.appendText("rclone is required. Install it: ");
        const code = document.createElement("code");
        code.textContent = info.command;
        descEl.appendChild(code);
        descEl.appendText(" ");
        const link = document.createElement("a");
        link.href = info.url;
        link.textContent = "More options";
        descEl.appendChild(link);
        setting.setDesc(descEl);
        setting.addButton(
          (btn) => btn.setButtonText("Check again").onClick(() => {
            this.hasChecked = false;
            this.checkConnection();
          })
        );
        break;
      }
      default: {
        setting.setDesc("Not connected to Google Drive");
        setting.addButton(
          (btn) => btn.setButtonText("Connect").setCta().onClick(() => this.connectDrive())
        );
        break;
      }
    }
  }
  async checkConnection() {
    this.hasChecked = true;
    this.connectionStatus = "checking";
    this.display();
    try {
      await this.plugin.drive.check();
      this.connectionStatus = "connected";
    } catch (e) {
      if (e instanceof DriveError && e.code === "binary-missing") {
        this.connectionStatus = "binary-missing";
      } else {
        this.connectionStatus = "idle";
      }
    }
    this.display();
  }
  async connectDrive() {
    this.connectionStatus = "connecting";
    this.display();
    const result = await this.plugin.drive.setupRemote(this.plugin.settings.rcloneRemote);
    if (result.ok) {
      this.connectionStatus = "connected";
      this.plugin.sidebarManager.refresh();
    } else if (result.code === "binary-missing") {
      this.connectionStatus = "binary-missing";
    } else if (result.code === "timeout") {
      this.connectionStatus = "error";
      this.connectionError = "Sign-in timed out. Click Retry to try again.";
    } else {
      this.connectionStatus = "error";
      this.connectionError = result.message;
    }
    this.display();
  }
};
