/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => LinkCommandPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  unfurlEnabled: true,
  unfurlOnPaste: false,
  unfurlTimeout: 1e4,
  cacheEnabled: true,
  cacheTTL: 168,
  // 7 days
  defaultFormat: "link",
  authDomains: [
    "slack.com",
    "app.slack.com",
    "notion.so",
    "docs.google.com",
    "drive.google.com",
    "sheets.google.com",
    "mail.google.com",
    "calendar.google.com",
    "linear.app",
    "figma.com",
    "www.figma.com",
    "miro.com",
    "trello.com",
    "asana.com",
    "jira.atlassian.com",
    "confluence.atlassian.com"
  ],
  showSidebarByDefault: true,
  recentHistoryLimit: 25
};

// src/UrlMetadataCache.ts
var CACHE_VERSION = 1;
var UrlMetadataCache = class {
  constructor(ttlHours, maxMemorySize, onSave) {
    this.memoryCache = /* @__PURE__ */ new Map();
    this.persistentData = null;
    this.ttlMs = ttlHours * 60 * 60 * 1e3;
    this.maxMemorySize = maxMemorySize;
    this.onSave = onSave;
  }
  /**
   * Load persistent cache from plugin data
   */
  async loadFromStorage(data) {
    if (!data || data.version !== CACHE_VERSION) {
      this.persistentData = { version: CACHE_VERSION, entries: {} };
      return;
    }
    this.persistentData = data;
    const now = Date.now();
    let changed = false;
    for (const [url, metadata] of Object.entries(this.persistentData.entries)) {
      if (this.isExpired(metadata, now)) {
        delete this.persistentData.entries[url];
        changed = true;
      }
    }
    if (changed) {
      await this.savePersistent();
    }
  }
  /**
   * Get metadata from cache (memory first, then persistent)
   */
  get(url) {
    var _a;
    const now = Date.now();
    const memoryEntry = this.memoryCache.get(url);
    if (memoryEntry && !this.isExpired(memoryEntry, now)) {
      return memoryEntry;
    }
    if ((_a = this.persistentData) == null ? void 0 : _a.entries[url]) {
      const persistentEntry = this.persistentData.entries[url];
      if (!this.isExpired(persistentEntry, now)) {
        this.setMemory(url, persistentEntry);
        return persistentEntry;
      }
    }
    return null;
  }
  /**
   * Store metadata in both memory and persistent cache
   */
  async set(url, metadata, sourcePage) {
    if (sourcePage) {
      const existing = this.get(url);
      const existingPages = (existing == null ? void 0 : existing.sourcePages) || [];
      if (!existingPages.includes(sourcePage)) {
        metadata.sourcePages = [...existingPages, sourcePage];
      } else {
        metadata.sourcePages = existingPages;
      }
    }
    this.setMemory(url, metadata);
    if (this.persistentData) {
      this.persistentData.entries[url] = metadata;
      await this.savePersistent();
    }
  }
  /**
   * Clear all caches
   */
  async clear() {
    this.memoryCache.clear();
    if (this.persistentData) {
      this.persistentData.entries = {};
      await this.savePersistent();
    }
  }
  /**
   * Get cache statistics
   */
  getStats() {
    return {
      memorySize: this.memoryCache.size,
      persistentSize: this.persistentData ? Object.keys(this.persistentData.entries).length : 0
    };
  }
  /**
   * Update TTL setting
   */
  setTTL(hours) {
    this.ttlMs = hours * 60 * 60 * 1e3;
  }
  /**
   * Get all cached entries sorted by fetchedAt (most recent first)
   */
  getRecentEntries(limit) {
    const entries = [];
    const now = Date.now();
    if (this.persistentData) {
      for (const metadata of Object.values(this.persistentData.entries)) {
        if (!this.isExpired(metadata, now)) {
          entries.push(metadata);
        }
      }
    }
    entries.sort((a, b) => b.fetchedAt - a.fetchedAt);
    return entries.slice(0, limit);
  }
  /**
   * Check if a URL is in the cache (without full get)
   */
  has(url) {
    return this.get(url) !== null;
  }
  setMemory(url, metadata) {
    if (this.memoryCache.size >= this.maxMemorySize) {
      const firstKey = this.memoryCache.keys().next().value;
      if (firstKey) {
        this.memoryCache.delete(firstKey);
      }
    }
    this.memoryCache.set(url, metadata);
  }
  isExpired(metadata, now) {
    return now - metadata.fetchedAt > this.ttlMs;
  }
  async savePersistent() {
    if (this.persistentData) {
      await this.onSave(this.persistentData);
    }
  }
};

// src/UrlMetadataProvider.ts
var import_obsidian = require("obsidian");
function parseHtmlMetadata(html, baseUrl) {
  const doc = new DOMParser().parseFromString(html, "text/html");
  const getMeta = (selectors) => {
    for (const selector of selectors) {
      const el = doc.querySelector(selector);
      if (el) {
        const content = el.getAttribute("content") || el.textContent;
        if (content == null ? void 0 : content.trim())
          return content.trim();
      }
    }
    return null;
  };
  const resolveUrl = (relative) => {
    if (!relative)
      return null;
    try {
      return new URL(relative, baseUrl).href;
    } catch (e) {
      return relative;
    }
  };
  const getFavicon = () => {
    const iconSelectors = [
      'link[rel="icon"]',
      'link[rel="shortcut icon"]',
      'link[rel="apple-touch-icon"]'
    ];
    for (const selector of iconSelectors) {
      const el = doc.querySelector(selector);
      if (el) {
        const href = el.getAttribute("href");
        if (href)
          return resolveUrl(href);
      }
    }
    try {
      return new URL("/favicon.ico", baseUrl).href;
    } catch (e) {
      return null;
    }
  };
  return {
    title: getMeta([
      'meta[property="og:title"]',
      'meta[name="twitter:title"]',
      "title"
    ]),
    description: getMeta([
      'meta[property="og:description"]',
      'meta[name="twitter:description"]',
      'meta[name="description"]'
    ]),
    image: resolveUrl(getMeta([
      'meta[property="og:image"]',
      'meta[name="twitter:image"]',
      'meta[name="twitter:image:src"]'
    ])),
    favicon: getFavicon(),
    siteName: getMeta(['meta[property="og:site_name"]']),
    type: getMeta(['meta[property="og:type"]']),
    publishedDate: getMeta([
      'meta[property="article:published_time"]',
      'meta[name="date"]',
      'meta[name="pubdate"]'
    ])
  };
}
var HtmlMetadataProvider = class {
  constructor() {
    this.name = "html";
    this.priority = 100;
  }
  // Low priority - runs after any API-based providers
  canHandle(_url) {
    return true;
  }
  async fetch(url, timeout) {
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url,
        method: "GET",
        headers: {
          "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
          "Accept-Language": "en-US,en;q=0.5"
        },
        throw: false
      });
      if (response.status >= 400) {
        console.warn(`[Link Command] HTTP ${response.status} for ${url}`);
        return {
          success: false,
          error: response.status === 401 || response.status === 403 ? "auth_required" : "network_error",
          errorMessage: `HTTP ${response.status}`
        };
      }
      const html = response.text;
      const parsed = parseHtmlMetadata(html, url);
      const loginIndicators = [
        "sign in",
        "log in",
        "login",
        "authenticate",
        "authorization required",
        "access denied"
      ];
      const titleLower = (parsed.title || "").toLowerCase();
      if (loginIndicators.some((ind) => titleLower.includes(ind))) {
        return {
          success: false,
          error: "auth_required",
          errorMessage: "Page requires authentication"
        };
      }
      const metadata = {
        url,
        title: parsed.title || null,
        description: parsed.description || null,
        image: parsed.image || null,
        favicon: parsed.favicon || null,
        siteName: parsed.siteName || null,
        type: parsed.type || null,
        publishedDate: parsed.publishedDate || null,
        fetchedAt: Date.now()
      };
      return {
        success: true,
        metadata
      };
    } catch (error) {
      console.error(`[Link Command] Fetch error for ${url}:`, error);
      return {
        success: false,
        error: "network_error",
        errorMessage: error instanceof Error ? error.message : "Unknown error"
      };
    }
  }
};
var AuthDomainProvider = class {
  constructor(authDomains) {
    this.name = "auth-domain";
    this.priority = 1;
    this.authDomains = authDomains;
  }
  updateDomains(domains) {
    this.authDomains = domains;
  }
  canHandle(url) {
    try {
      const hostname = new URL(url).hostname;
      return this.authDomains.some(
        (domain) => hostname === domain || hostname.endsWith("." + domain)
      );
    } catch (e) {
      return false;
    }
  }
  async fetch(url, _timeout) {
    let hostname;
    try {
      hostname = new URL(url).hostname;
    } catch (e) {
      hostname = "unknown";
    }
    return {
      success: false,
      error: "auth_required",
      errorMessage: `${hostname} requires authentication. Add an API provider or remove from auth domains list.`
    };
  }
};

// src/UrlUnfurlService.ts
var URL_REGEX = /^https?:\/\/[^\s]+$/i;
var UrlUnfurlService = class {
  constructor(settings, onSaveCache) {
    this.providers = [];
    this.settings = settings;
    this.cache = new UrlMetadataCache(
      settings.cacheTTL,
      100,
      // max memory entries
      onSaveCache
    );
    this.authDomainProvider = new AuthDomainProvider(settings.authDomains);
    this.providers.push(this.authDomainProvider);
    this.providers.push(new HtmlMetadataProvider());
    this.sortProviders();
  }
  /**
   * Load cached data from storage
   */
  async loadCache(data) {
    await this.cache.loadFromStorage(data);
  }
  /**
   * Update settings
   */
  updateSettings(settings) {
    this.settings = settings;
    this.cache.setTTL(settings.cacheTTL);
    this.authDomainProvider.updateDomains(settings.authDomains);
  }
  /**
   * Register a custom provider (e.g., API-based provider for specific services)
   */
  registerProvider(provider) {
    this.providers.push(provider);
    this.sortProviders();
  }
  /**
   * Unfurl a URL - get its metadata
   * @param sourcePage - Optional file path where this URL was unfurled (for tracking)
   */
  async unfurl(url, forceRefresh = false, sourcePage) {
    if (!this.isValidUrl(url)) {
      return {
        success: false,
        error: "invalid_url",
        errorMessage: "Invalid URL format"
      };
    }
    if (!forceRefresh && this.settings.cacheEnabled) {
      const cached = this.cache.get(url);
      if (cached) {
        if (sourcePage && this.settings.cacheEnabled) {
          await this.cache.set(url, cached, sourcePage);
        }
        return { success: true, metadata: cached };
      }
    }
    const provider = this.providers.find((p) => p.canHandle(url));
    if (!provider) {
      return {
        success: false,
        error: "network_error",
        errorMessage: "No provider available for this URL"
      };
    }
    const result = await provider.fetch(url, this.settings.unfurlTimeout);
    if (result.success && result.metadata && this.settings.cacheEnabled) {
      await this.cache.set(url, result.metadata, sourcePage);
    }
    return result;
  }
  /**
   * Unfurl multiple URLs in parallel
   */
  async unfurlBatch(urls) {
    const results = /* @__PURE__ */ new Map();
    const promises = urls.map(async (url) => {
      const result = await this.unfurl(url);
      results.set(url, result);
    });
    await Promise.all(promises);
    return results;
  }
  /**
   * Check if a string is a valid URL
   */
  isValidUrl(url) {
    if (!URL_REGEX.test(url))
      return false;
    try {
      new URL(url);
      return true;
    } catch (e) {
      return false;
    }
  }
  /**
   * Extract URLs from text
   */
  extractUrls(text) {
    const urlRegex = /https?:\/\/[^\s\]\)]+/g;
    return text.match(urlRegex) || [];
  }
  /**
   * Get cache statistics
   */
  getCacheStats() {
    return this.cache.getStats();
  }
  /**
   * Clear cache
   */
  async clearCache() {
    await this.cache.clear();
  }
  /**
   * Get recent entries from cache
   */
  getRecentEntries(limit) {
    return this.cache.getRecentEntries(limit);
  }
  /**
   * Check if URL is in cache
   */
  isCached(url) {
    return this.cache.has(url);
  }
  /**
   * Get cached metadata for a URL (without fetching)
   */
  getCached(url) {
    return this.cache.get(url);
  }
  sortProviders() {
    this.providers.sort((a, b) => a.priority - b.priority);
  }
};

// src/UrlUnfurlTooltip.ts
var UrlUnfurlTooltip = class {
  constructor(app) {
    this.tooltip = null;
    this.closeHandler = null;
    this.escapeHandler = null;
    this.component = null;
    this.currentUrl = "";
    this.actions = null;
    this.app = app;
  }
  /**
   * Show tooltip with loading state
   */
  showLoading(editor, url, actions) {
    this.show(editor, url, { loading: true }, actions);
  }
  /**
   * Show tooltip with metadata
   */
  showMetadata(editor, url, metadata, actions) {
    this.show(editor, url, { metadata }, actions);
  }
  /**
   * Show tooltip with error
   */
  showError(editor, url, error, actions) {
    this.show(editor, url, { error }, actions);
  }
  /**
   * Update existing tooltip content
   */
  updateContent(result) {
    if (!this.tooltip)
      return;
    const contentEl = this.tooltip.querySelector(".link-tooltip-content");
    if (!contentEl)
      return;
    contentEl.empty();
    if (result.success && result.metadata) {
      this.renderMetadata(contentEl, result.metadata);
      this.tooltip.classList.remove("link-tooltip-loading", "link-tooltip-error");
      this.createActionsBar(result.metadata);
    } else {
      this.renderError(contentEl, result.errorMessage || "Failed to fetch link");
      this.tooltip.classList.remove("link-tooltip-loading");
      this.tooltip.classList.add("link-tooltip-error");
    }
  }
  /**
   * Close the tooltip
   */
  close() {
    if (this.component) {
      this.component.unload();
      this.component = null;
    }
    if (this.tooltip) {
      this.tooltip.remove();
      this.tooltip = null;
    }
    if (this.closeHandler) {
      document.removeEventListener("click", this.closeHandler);
      this.closeHandler = null;
    }
    if (this.escapeHandler) {
      document.removeEventListener("keydown", this.escapeHandler);
      this.escapeHandler = null;
    }
    this.currentUrl = "";
    this.actions = null;
  }
  show(editor, url, content, actions) {
    this.close();
    this.currentUrl = url;
    this.actions = actions;
    const cm = editor.cm;
    if (!cm)
      return;
    const cursor = editor.getCursor("to");
    let coords = null;
    if (cm.coordsAtPos) {
      const line = cm.state.doc.line(cursor.line + 1);
      const pos = line.from + cursor.ch;
      coords = cm.coordsAtPos(pos);
    } else if (cm.charCoords) {
      coords = cm.charCoords({ line: cursor.line, ch: cursor.ch }, "page");
    }
    if (!coords)
      return;
    this.tooltip = document.createElement("div");
    this.tooltip.className = "link-tooltip";
    if (content.loading) {
      this.tooltip.classList.add("link-tooltip-loading");
    }
    if (content.error) {
      this.tooltip.classList.add("link-tooltip-error");
    }
    const headerEl = this.tooltip.createEl("div", { cls: "link-tooltip-header" });
    headerEl.createEl("span", { cls: "link-tooltip-logo", text: "Link" });
    try {
      const hostname = new URL(url).hostname;
      headerEl.createEl("span", { cls: "link-tooltip-domain", text: hostname });
    } catch (e) {
    }
    const closeBtn = headerEl.createEl("button", {
      cls: "link-tooltip-close",
      text: "\xD7",
      attr: { "aria-label": "Close" }
    });
    closeBtn.addEventListener("click", () => this.close());
    const contentEl = this.tooltip.createEl("div", { cls: "link-tooltip-content" });
    if (content.loading) {
      contentEl.createEl("span", { cls: "link-tooltip-spinner" });
      contentEl.createSpan({ text: "Fetching link..." });
    } else if (content.metadata) {
      this.renderMetadata(contentEl, content.metadata);
      this.createActionsBar(content.metadata);
    } else if (content.error) {
      this.renderError(contentEl, content.error);
    }
    this.tooltip.style.position = "fixed";
    this.tooltip.style.top = `${coords.bottom + 8}px`;
    this.tooltip.style.left = `${coords.left}px`;
    document.body.appendChild(this.tooltip);
    this.adjustPosition(coords);
  }
  renderMetadata(container, metadata) {
    if (metadata.image) {
      const imgContainer = container.createEl("div", { cls: "link-tooltip-image-container" });
      const img = imgContainer.createEl("img", {
        cls: "link-tooltip-image",
        attr: { src: metadata.image, alt: metadata.title || "Preview" }
      });
      img.addEventListener("error", () => {
        imgContainer.remove();
      });
    }
    if (metadata.title) {
      container.createEl("div", { cls: "link-tooltip-title", text: metadata.title });
    } else {
      container.createEl("div", { cls: "link-tooltip-title link-tooltip-no-title", text: "No title available" });
    }
    if (metadata.description) {
      const desc = container.createEl("div", { cls: "link-tooltip-description" });
      const maxLen = 200;
      desc.textContent = metadata.description.length > maxLen ? metadata.description.slice(0, maxLen) + "..." : metadata.description;
    }
    if (metadata.siteName || metadata.favicon) {
      const siteRow = container.createEl("div", { cls: "link-tooltip-site" });
      if (metadata.favicon) {
        const favicon = siteRow.createEl("img", {
          cls: "link-tooltip-favicon",
          attr: { src: metadata.favicon, alt: "" }
        });
        favicon.addEventListener("error", () => {
          favicon.remove();
        });
      }
      if (metadata.siteName) {
        siteRow.createEl("span", { text: metadata.siteName });
      }
    }
  }
  renderError(container, error) {
    container.createEl("div", { cls: "link-tooltip-error-message", text: error });
    if (this.actions) {
      const retryBtn = container.createEl("button", {
        cls: "link-tooltip-btn link-tooltip-retry-btn",
        text: "Retry"
      });
      retryBtn.addEventListener("click", () => {
        if (this.actions) {
          this.actions.onRetry();
        }
      });
    }
  }
  createActionsBar(metadata) {
    if (!this.tooltip || !this.actions)
      return;
    const existingActions = this.tooltip.querySelector(".link-tooltip-actions");
    if (existingActions) {
      existingActions.remove();
    }
    const actionsEl = this.tooltip.createEl("div", { cls: "link-tooltip-actions" });
    const linkBtn = actionsEl.createEl("button", {
      cls: "link-tooltip-btn",
      text: "Insert Link"
    });
    linkBtn.addEventListener("click", () => {
      if (this.actions) {
        this.actions.onInsertLink(metadata);
      }
      this.close();
    });
    const cardBtn = actionsEl.createEl("button", {
      cls: "link-tooltip-btn",
      text: "Insert Card"
    });
    cardBtn.addEventListener("click", () => {
      if (this.actions) {
        this.actions.onInsertCard(metadata);
      }
      this.close();
    });
    const copyBtn = actionsEl.createEl("button", {
      cls: "link-tooltip-btn link-tooltip-copy-btn",
      text: "Copy"
    });
    copyBtn.addEventListener("click", async () => {
      if (this.actions) {
        this.actions.onCopy(metadata);
      }
    });
  }
  adjustPosition(coords) {
    if (!this.tooltip)
      return;
    const rect = this.tooltip.getBoundingClientRect();
    const margin = 10;
    if (rect.right > window.innerWidth - margin) {
      const newLeft = Math.max(margin, window.innerWidth - rect.width - margin);
      this.tooltip.style.left = `${newLeft}px`;
    }
    if (rect.left < margin) {
      this.tooltip.style.left = `${margin}px`;
    }
    if (rect.bottom > window.innerHeight - margin) {
      const aboveTop = coords.top - rect.height - 8;
      if (aboveTop >= margin) {
        this.tooltip.style.top = `${aboveTop}px`;
      } else {
        this.tooltip.style.top = `${margin}px`;
        const maxHeight = window.innerHeight - 2 * margin;
        if (rect.height > maxHeight) {
          this.tooltip.style.maxHeight = `${maxHeight}px`;
          this.tooltip.style.overflowY = "auto";
        }
      }
    }
    this.closeHandler = (e) => {
      if (this.tooltip && !this.tooltip.contains(e.target)) {
        this.close();
      }
    };
    this.escapeHandler = (e) => {
      if (e.key === "Escape") {
        this.close();
      }
    };
    setTimeout(() => {
      document.addEventListener("click", this.closeHandler);
      document.addEventListener("keydown", this.escapeHandler);
    }, 100);
  }
};

// src/LinkCardProcessor.ts
function parseCardContent(source) {
  const result = {};
  const lines = source.trim().split("\n");
  for (const line of lines) {
    const colonIndex = line.indexOf(":");
    if (colonIndex > 0) {
      const key = line.slice(0, colonIndex).trim().toLowerCase();
      const value = line.slice(colonIndex + 1).trim();
      if (key && value) {
        result[key] = value;
      }
    }
  }
  return result;
}
var LinkCardProcessor = class {
  constructor(app, unfurlService) {
    this.app = app;
    this.unfurlService = unfurlService;
  }
  /**
   * Process a link-card code block
   */
  async process(source, el, ctx) {
    const data = parseCardContent(source);
    if (!data.url) {
      this.renderError(el, "Missing URL in link-card");
      return;
    }
    const card = el.createEl("div", { cls: "link-card" });
    if (data.title) {
      this.renderCard(card, {
        url: data.url,
        title: data.title,
        description: data.description || null,
        image: data.image || null,
        favicon: data.favicon || null,
        siteName: data.sitename || null
      });
      return;
    }
    card.createEl("div", { cls: "link-card-loading", text: "Loading preview..." });
    const result = await this.unfurlService.unfurl(data.url);
    card.empty();
    if (result.success && result.metadata) {
      this.renderCard(card, {
        url: data.url,
        title: data.title || result.metadata.title,
        description: data.description || result.metadata.description,
        image: data.image || result.metadata.image,
        favicon: data.favicon || result.metadata.favicon,
        siteName: data.sitename || result.metadata.siteName
      });
    } else {
      this.renderFallback(card, data.url, result.errorMessage);
    }
  }
  renderCard(container, data) {
    const link = container.createEl("a", {
      cls: "link-card-link",
      attr: { href: data.url, target: "_blank", rel: "noopener noreferrer" }
    });
    if (data.image) {
      const imageContainer = link.createEl("div", { cls: "link-card-image-container" });
      const img = imageContainer.createEl("img", {
        cls: "link-card-image",
        attr: { src: data.image, alt: data.title || "Preview" }
      });
      img.addEventListener("error", () => {
        imageContainer.remove();
      });
    }
    const content = link.createEl("div", { cls: "link-card-content" });
    content.createEl("div", {
      cls: "link-card-title",
      text: data.title || data.url
    });
    if (data.description) {
      const desc = content.createEl("div", { cls: "link-card-description" });
      const maxLen = 150;
      desc.textContent = data.description.length > maxLen ? data.description.slice(0, maxLen) + "..." : data.description;
    }
    const footer = content.createEl("div", { cls: "link-card-footer" });
    if (data.favicon) {
      const favicon = footer.createEl("img", {
        cls: "link-card-favicon",
        attr: { src: data.favicon, alt: "" }
      });
      favicon.addEventListener("error", () => {
        favicon.remove();
      });
    }
    try {
      const hostname = new URL(data.url).hostname;
      footer.createEl("span", { cls: "link-card-domain", text: data.siteName || hostname });
    } catch (e) {
    }
  }
  renderFallback(container, url, error) {
    const fallback = container.createEl("div", { cls: "link-card-fallback" });
    fallback.createEl("a", {
      cls: "link-card-fallback-link",
      text: url,
      attr: { href: url, target: "_blank", rel: "noopener noreferrer" }
    });
    if (error) {
      fallback.createEl("span", { cls: "link-card-fallback-error", text: ` (${error})` });
    }
  }
  renderError(container, message) {
    container.createEl("div", { cls: "link-card-error", text: message });
  }
};

// src/LinkSidebarView.ts
var import_obsidian2 = require("obsidian");
var VIEW_TYPE_LINK_SIDEBAR = "link-command-sidebar";
var LinkSidebarView = class extends import_obsidian2.ItemView {
  constructor(leaf, unfurlService, settings, onOpenUrl, onShowAbout, onOpenSettings) {
    super(leaf);
    this.activeFileListener = null;
    this.unfurlService = unfurlService;
    this.settings = settings;
    this.onOpenUrl = onOpenUrl;
    this.onShowAbout = onShowAbout;
    this.onOpenSettings = onOpenSettings;
  }
  getViewType() {
    return VIEW_TYPE_LINK_SIDEBAR;
  }
  getDisplayText() {
    return "Links";
  }
  getIcon() {
    return "link";
  }
  async onOpen() {
    this.activeFileListener = () => this.render();
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", this.activeFileListener)
    );
    this.registerEvent(
      this.app.workspace.on("file-open", this.activeFileListener)
    );
    await this.render();
  }
  async onClose() {
  }
  updateSettings(settings) {
    this.settings = settings;
    this.render();
  }
  async render() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("link-command-sidebar");
    this.renderHeader(container);
    const content = container.createEl("div", { cls: "link-sidebar-content" });
    const activeFile = this.app.workspace.getActiveFile();
    await this.renderPageLinksSection(content, activeFile);
    this.renderRecentHistorySection(content);
  }
  renderHeader(container) {
    const headerDiv = container.createEl("div", { cls: "link-sidebar-header" });
    const titleEl = headerDiv.createEl("h4", { cls: "link-sidebar-title" });
    const logoEl = titleEl.createEl("span", { cls: "link-command-logo clickable-logo", text: "L\u2318" });
    logoEl.addEventListener("click", () => this.onShowAbout());
    titleEl.appendText(" Link Command");
    const menuBtn = headerDiv.createEl("button", {
      cls: "clickable-icon link-sidebar-menu-btn",
      attr: { "aria-label": "Menu" }
    });
    menuBtn.innerHTML = '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="5" r="1"></circle><circle cx="12" cy="12" r="1"></circle><circle cx="12" cy="19" r="1"></circle></svg>';
    menuBtn.addEventListener("click", (evt) => {
      const menu = new import_obsidian2.Menu();
      menu.addItem((item) => {
        item.setTitle("Refresh").setIcon("refresh-cw").onClick(async () => {
          menuBtn.addClass("rotating");
          await this.render();
          setTimeout(() => menuBtn.removeClass("rotating"), 500);
        });
      });
      menu.addSeparator();
      menu.addItem((item) => {
        item.setTitle("About").setIcon("info").onClick(() => this.onShowAbout());
      });
      menu.addItem((item) => {
        item.setTitle("Settings").setIcon("settings").onClick(() => this.onOpenSettings());
      });
      menu.showAtMouseEvent(evt);
    });
  }
  async renderPageLinksSection(container, activeFile) {
    const section = container.createEl("div", { cls: "link-sidebar-section" });
    const header = section.createEl("div", { cls: "link-sidebar-section-header" });
    header.createEl("span", { text: "Page Links", cls: "link-sidebar-section-title" });
    const listContainer = section.createEl("div", { cls: "link-sidebar-list" });
    if (!activeFile) {
      listContainer.createEl("div", { cls: "link-sidebar-empty", text: "No file open" });
      return;
    }
    const fileContent = await this.app.vault.read(activeFile);
    const pageLinks = this.extractLinksFromContent(fileContent);
    if (pageLinks.length === 0) {
      listContainer.createEl("div", { cls: "link-sidebar-empty", text: "No links in this file" });
      return;
    }
    header.createEl("span", { cls: "link-sidebar-count", text: `(${pageLinks.length})` });
    for (const link of pageLinks) {
      this.renderLinkItem(listContainer, link, activeFile);
    }
  }
  renderRecentHistorySection(container) {
    const section = container.createEl("div", { cls: "link-sidebar-section" });
    const header = section.createEl("div", { cls: "link-sidebar-section-header" });
    header.createEl("span", { text: "Recent History", cls: "link-sidebar-section-title" });
    const listContainer = section.createEl("div", { cls: "link-sidebar-list" });
    const recentEntries = this.unfurlService.getRecentEntries(this.settings.recentHistoryLimit);
    if (recentEntries.length === 0) {
      listContainer.createEl("div", { cls: "link-sidebar-empty", text: "No unfurled links yet" });
      return;
    }
    header.createEl("span", { cls: "link-sidebar-count", text: `(${recentEntries.length})` });
    for (const metadata of recentEntries) {
      this.renderHistoryItem(listContainer, metadata);
    }
  }
  extractLinksFromContent(content) {
    const links = [];
    const urlRegex = /https?:\/\/[^\s\]\)>"']+/g;
    const lines = content.split("\n");
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      let match;
      while ((match = urlRegex.exec(line)) !== null) {
        const url = match[0];
        if (!links.some((l) => l.url === url)) {
          const cached = this.unfurlService.getCached(url);
          links.push({
            url,
            lineNumber: i,
            isCached: cached !== null,
            metadata: cached || void 0
          });
        }
      }
    }
    return links;
  }
  renderLinkItem(container, link, activeFile) {
    var _a;
    const item = container.createEl("div", { cls: "link-sidebar-item" });
    const status = item.createEl("span", {
      cls: `link-sidebar-status ${link.isCached ? "link-sidebar-status-cached" : "link-sidebar-status-pending"}`,
      attr: { title: link.isCached ? "Unfurled" : "Not unfurled" }
    });
    const content = item.createEl("div", { cls: "link-sidebar-item-content" });
    if ((_a = link.metadata) == null ? void 0 : _a.title) {
      content.createEl("div", { cls: "link-sidebar-item-title", text: link.metadata.title });
      content.createEl("div", { cls: "link-sidebar-item-url", text: this.truncateUrl(link.url) });
    } else {
      content.createEl("div", { cls: "link-sidebar-item-title", text: this.truncateUrl(link.url) });
    }
    item.addEventListener("click", () => {
      this.onOpenUrl(link.url, link.lineNumber);
    });
    item.addEventListener("contextmenu", (e) => {
      e.preventDefault();
      this.showLinkContextMenu(e, link, activeFile);
    });
  }
  renderHistoryItem(container, metadata) {
    const item = container.createEl("div", { cls: "link-sidebar-item link-sidebar-history-item" });
    if (metadata.favicon) {
      const favicon = item.createEl("img", {
        cls: "link-sidebar-favicon",
        attr: { src: metadata.favicon, alt: "" }
      });
      favicon.addEventListener("error", () => favicon.remove());
    } else {
      item.createEl("span", { cls: "link-sidebar-favicon-placeholder" });
    }
    const content = item.createEl("div", { cls: "link-sidebar-item-content" });
    content.createEl("div", {
      cls: "link-sidebar-item-title",
      text: metadata.title || this.truncateUrl(metadata.url)
    });
    const metaRow = content.createEl("div", { cls: "link-sidebar-item-meta" });
    metaRow.createEl("span", { cls: "link-sidebar-item-url", text: this.truncateUrl(metadata.url) });
    if (metadata.sourcePages && metadata.sourcePages.length > 0) {
      const sourceCount = metadata.sourcePages.length;
      const sourceText = sourceCount === 1 ? this.getFileName(metadata.sourcePages[0]) : `${sourceCount} pages`;
      metaRow.createEl("span", { cls: "link-sidebar-item-source", text: `\xB7 ${sourceText}` });
    }
    const timeAgo = this.formatTimeAgo(metadata.fetchedAt);
    metaRow.createEl("span", { cls: "link-sidebar-item-time", text: `\xB7 ${timeAgo}` });
    item.addEventListener("click", () => {
      window.open(metadata.url, "_blank");
    });
    item.addEventListener("contextmenu", (e) => {
      e.preventDefault();
      this.showHistoryContextMenu(e, metadata);
    });
  }
  showLinkContextMenu(e, link, activeFile) {
    var _a;
    const menu = new import_obsidian2.Menu();
    menu.addItem((item) => {
      item.setTitle("Unfurl link").setIcon("refresh-cw").onClick(async () => {
        await this.unfurlService.unfurl(link.url, true, activeFile.path);
        this.render();
      });
    });
    menu.addItem((item) => {
      item.setTitle("Copy URL").setIcon("copy").onClick(async () => {
        await navigator.clipboard.writeText(link.url);
      });
    });
    if ((_a = link.metadata) == null ? void 0 : _a.title) {
      menu.addItem((item) => {
        item.setTitle("Copy as markdown link").setIcon("link").onClick(async () => {
          const mdLink = `[${link.metadata.title}](${link.url})`;
          await navigator.clipboard.writeText(mdLink);
        });
      });
    }
    menu.addItem((item) => {
      item.setTitle("Open in browser").setIcon("external-link").onClick(() => {
        window.open(link.url, "_blank");
      });
    });
    menu.showAtMouseEvent(e);
  }
  showHistoryContextMenu(e, metadata) {
    const menu = new import_obsidian2.Menu();
    menu.addItem((item) => {
      item.setTitle("Copy URL").setIcon("copy").onClick(async () => {
        await navigator.clipboard.writeText(metadata.url);
      });
    });
    if (metadata.title) {
      menu.addItem((item) => {
        item.setTitle("Copy as markdown link").setIcon("link").onClick(async () => {
          const mdLink = `[${metadata.title}](${metadata.url})`;
          await navigator.clipboard.writeText(mdLink);
        });
      });
    }
    menu.addItem((item) => {
      item.setTitle("Open in browser").setIcon("external-link").onClick(() => {
        window.open(metadata.url, "_blank");
      });
    });
    if (metadata.sourcePages && metadata.sourcePages.length > 0) {
      menu.addSeparator();
      menu.addItem((item) => {
        item.setTitle("Source pages").setIcon("file-text").setDisabled(true);
      });
      for (const sourcePath of metadata.sourcePages.slice(0, 5)) {
        menu.addItem((item) => {
          item.setTitle(`  ${this.getFileName(sourcePath)}`).onClick(async () => {
            const file = this.app.vault.getAbstractFileByPath(sourcePath);
            if (file instanceof import_obsidian2.TFile) {
              await this.app.workspace.getLeaf().openFile(file);
            }
          });
        });
      }
    }
    menu.showAtMouseEvent(e);
  }
  truncateUrl(url, maxLength = 50) {
    try {
      const parsed = new URL(url);
      const display = parsed.hostname + parsed.pathname;
      if (display.length > maxLength) {
        return display.slice(0, maxLength - 3) + "...";
      }
      return display;
    } catch (e) {
      return url.length > maxLength ? url.slice(0, maxLength - 3) + "..." : url;
    }
  }
  getFileName(path) {
    const parts = path.split("/");
    return parts[parts.length - 1].replace(/\.md$/, "");
  }
  formatTimeAgo(timestamp) {
    const seconds = Math.floor((Date.now() - timestamp) / 1e3);
    if (seconds < 60)
      return "just now";
    if (seconds < 3600)
      return `${Math.floor(seconds / 60)}m ago`;
    if (seconds < 86400)
      return `${Math.floor(seconds / 3600)}h ago`;
    if (seconds < 604800)
      return `${Math.floor(seconds / 86400)}d ago`;
    return new Date(timestamp).toLocaleDateString();
  }
};

// main.ts
var LinkCommandPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.cacheData = null;
    this.sidebarView = null;
  }
  async onload() {
    await this.loadSettings();
    this.unfurlService = new UrlUnfurlService(
      this.settings,
      async (data) => {
        this.cacheData = data;
        await this.saveData({ settings: this.settings, cache: data });
      }
    );
    const savedData = await this.loadData();
    if (savedData == null ? void 0 : savedData.cache) {
      await this.unfurlService.loadCache(savedData.cache);
    }
    this.tooltip = new UrlUnfurlTooltip(this.app);
    this.linkCardProcessor = new LinkCardProcessor(this.app, this.unfurlService);
    this.registerMarkdownCodeBlockProcessor("link-card", async (source, el, ctx) => {
      await this.linkCardProcessor.process(source, el, ctx);
    });
    this.registerView(
      VIEW_TYPE_LINK_SIDEBAR,
      (leaf) => {
        this.sidebarView = new LinkSidebarView(
          leaf,
          this.unfurlService,
          this.settings,
          (url, lineNumber) => this.navigateToUrl(url, lineNumber),
          () => this.showAbout(),
          () => this.openSettings()
        );
        return this.sidebarView;
      }
    );
    this.addRibbonIcon("link", "Link Command", () => {
      this.toggleSidebar();
    });
    if (this.settings.showSidebarByDefault) {
      this.app.workspace.onLayoutReady(() => {
        this.activateSidebar();
      });
    }
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu, editor) => {
        if (!this.settings.unfurlEnabled)
          return;
        const url = this.detectUrlAtCursor(editor);
        if (url) {
          menu.addItem((item) => {
            item.setTitle("Unfurl link...").setIcon("link").onClick(() => {
              this.unfurlUrl(editor, url);
            });
          });
        }
      })
    );
    this.registerEvent(
      this.app.workspace.on("editor-paste", async (evt, editor) => {
        var _a, _b;
        if (!this.settings.unfurlEnabled || !this.settings.unfurlOnPaste)
          return;
        const clipboardText = (_b = (_a = evt.clipboardData) == null ? void 0 : _a.getData("text/plain")) == null ? void 0 : _b.trim();
        if (clipboardText && this.unfurlService.isValidUrl(clipboardText)) {
          evt.preventDefault();
          await this.handlePasteUrl(editor, clipboardText);
        }
      })
    );
    this.addCommand({
      id: "unfurl-url",
      name: "Unfurl URL at cursor",
      editorCallback: (editor) => {
        const url = this.detectUrlAtCursor(editor);
        if (url) {
          this.unfurlUrl(editor, url);
        } else {
          new import_obsidian3.Notice("No URL found at cursor");
        }
      }
    });
    this.addCommand({
      id: "insert-link-card",
      name: "Insert link card",
      editorCallback: async (editor) => {
        const url = this.detectUrlAtCursor(editor);
        if (url) {
          await this.insertLinkCard(editor, url);
        } else {
          new import_obsidian3.Notice("No URL found at cursor");
        }
      }
    });
    this.addCommand({
      id: "clear-link-cache",
      name: "Clear link cache",
      callback: async () => {
        var _a;
        await this.unfurlService.clearCache();
        new import_obsidian3.Notice("Link cache cleared");
        (_a = this.sidebarView) == null ? void 0 : _a.render();
      }
    });
    this.addCommand({
      id: "toggle-link-sidebar",
      name: "Toggle link sidebar",
      callback: () => {
        this.toggleSidebar();
      }
    });
    this.addSettingTab(new LinkCommandSettingTab(this.app, this));
  }
  onunload() {
    this.tooltip.close();
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_LINK_SIDEBAR);
  }
  /**
   * Activate the sidebar view
   */
  async activateSidebar() {
    const existing = this.app.workspace.getLeavesOfType(VIEW_TYPE_LINK_SIDEBAR);
    if (existing.length > 0) {
      this.app.workspace.revealLeaf(existing[0]);
      return;
    }
    const rightLeaf = this.app.workspace.getRightLeaf(false);
    if (rightLeaf) {
      await rightLeaf.setViewState({
        type: VIEW_TYPE_LINK_SIDEBAR,
        active: true
      });
    }
  }
  /**
   * Toggle the sidebar view
   */
  async toggleSidebar() {
    const existing = this.app.workspace.getLeavesOfType(VIEW_TYPE_LINK_SIDEBAR);
    if (existing.length > 0) {
      existing[0].detach();
    } else {
      await this.activateSidebar();
    }
  }
  /**
   * Navigate to a URL in the active file
   */
  navigateToUrl(url, lineNumber) {
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile)
      return;
    const leaf = this.app.workspace.getLeaf();
    leaf.openFile(activeFile).then(() => {
      const view = leaf.view;
      if (view && "editor" in view) {
        const editor = view.editor;
        if (editor) {
          editor.setCursor({ line: lineNumber, ch: 0 });
          editor.scrollIntoView({ from: { line: lineNumber, ch: 0 }, to: { line: lineNumber, ch: 0 } }, true);
        }
      }
    });
  }
  /**
   * Show the About modal
   */
  showAbout() {
    const stats = this.unfurlService.getCacheStats();
    new import_obsidian3.Notice(
      `L\u2318 Link Command v${this.manifest.version}

Cached links: ${stats.persistentSize}
Memory cache: ${stats.memorySize}`,
      5e3
    );
  }
  /**
   * Open plugin settings
   */
  openSettings() {
    this.app.setting.open();
    this.app.setting.openTabById("link-command");
  }
  async loadSettings() {
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data == null ? void 0 : data.settings);
  }
  async saveSettings() {
    var _a;
    await this.saveData({ settings: this.settings, cache: this.cacheData });
    this.unfurlService.updateSettings(this.settings);
    (_a = this.sidebarView) == null ? void 0 : _a.updateSettings(this.settings);
  }
  /**
   * Detect if cursor is on a URL and return it
   */
  detectUrlAtCursor(editor) {
    const cursor = editor.getCursor();
    const line = editor.getLine(cursor.line);
    const urlRegex = /https?:\/\/[^\s\]\)]+/g;
    let match;
    while ((match = urlRegex.exec(line)) !== null) {
      const start = match.index;
      const end = start + match[0].length;
      if (cursor.ch >= start && cursor.ch <= end) {
        return match[0];
      }
    }
    const selection = editor.getSelection();
    if (selection && this.unfurlService.isValidUrl(selection.trim())) {
      return selection.trim();
    }
    return null;
  }
  /**
   * Unfurl URL and show tooltip
   */
  async unfurlUrl(editor, url) {
    var _a;
    const actions = {
      onInsertLink: (metadata) => {
        this.insertMarkdownLink(editor, url, metadata);
      },
      onInsertCard: (metadata) => {
        this.insertCardBlock(editor, url, metadata);
      },
      onCopy: async (metadata) => {
        const text = `[${metadata.title || url}](${url})`;
        await navigator.clipboard.writeText(text);
        new import_obsidian3.Notice("Link copied to clipboard");
      },
      onRetry: () => {
        this.unfurlUrl(editor, url);
      }
    };
    this.tooltip.showLoading(editor, url, actions);
    const activeFile = this.app.workspace.getActiveFile();
    const result = await this.unfurlService.unfurl(url, false, activeFile == null ? void 0 : activeFile.path);
    this.tooltip.updateContent(result);
    (_a = this.sidebarView) == null ? void 0 : _a.render();
  }
  /**
   * Handle paste of URL
   */
  async handlePasteUrl(editor, url) {
    var _a;
    editor.replaceSelection(url);
    const activeFile = this.app.workspace.getActiveFile();
    const result = await this.unfurlService.unfurl(url, false, activeFile == null ? void 0 : activeFile.path);
    if (result.success && ((_a = result.metadata) == null ? void 0 : _a.title)) {
      const cursor = editor.getCursor();
      const line = editor.getLine(cursor.line);
      const urlIndex = line.lastIndexOf(url);
      if (urlIndex >= 0) {
        const from = { line: cursor.line, ch: urlIndex };
        const to = { line: cursor.line, ch: urlIndex + url.length };
        const markdownLink = `[${result.metadata.title}](${url})`;
        editor.replaceRange(markdownLink, from, to);
      }
    }
  }
  /**
   * Insert markdown link at cursor
   */
  insertMarkdownLink(editor, url, metadata) {
    const title = metadata.title || url;
    const markdownLink = `[${title}](${url})`;
    const selection = editor.getSelection();
    if (selection === url) {
      editor.replaceSelection(markdownLink);
    } else {
      const cursor = editor.getCursor();
      const line = editor.getLine(cursor.line);
      const urlIndex = line.indexOf(url);
      if (urlIndex >= 0) {
        const from = { line: cursor.line, ch: urlIndex };
        const to = { line: cursor.line, ch: urlIndex + url.length };
        editor.replaceRange(markdownLink, from, to);
      } else {
        editor.replaceSelection(markdownLink);
      }
    }
  }
  /**
   * Insert link card code block
   */
  insertCardBlock(editor, url, metadata) {
    const lines = ["```link-card", `url: ${url}`];
    if (metadata.title) {
      lines.push(`title: ${metadata.title}`);
    }
    if (metadata.description) {
      const desc = metadata.description.replace(/\n/g, " ").slice(0, 200);
      lines.push(`description: ${desc}`);
    }
    if (metadata.image) {
      lines.push(`image: ${metadata.image}`);
    }
    lines.push("```");
    const cardBlock = lines.join("\n");
    const selection = editor.getSelection();
    if (selection === url) {
      editor.replaceSelection(cardBlock);
    } else {
      const cursor = editor.getCursor();
      const line = editor.getLine(cursor.line);
      const urlIndex = line.indexOf(url);
      if (urlIndex >= 0 && line.trim() === url) {
        const from = { line: cursor.line, ch: 0 };
        const to = { line: cursor.line, ch: line.length };
        editor.replaceRange(cardBlock, from, to);
      } else {
        editor.replaceSelection(cardBlock);
      }
    }
  }
  /**
   * Insert link card for URL at cursor
   */
  async insertLinkCard(editor, url) {
    const result = await this.unfurlService.unfurl(url);
    if (result.success && result.metadata) {
      this.insertCardBlock(editor, url, result.metadata);
    } else {
      const basicCard = `\`\`\`link-card
url: ${url}
\`\`\``;
      editor.replaceSelection(basicCard);
    }
  }
};
var LinkCommandSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Link Command Settings" });
    new import_obsidian3.Setting(containerEl).setName("Enable URL unfurling").setDesc("Show link previews via context menu and commands").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.unfurlEnabled).onChange(async (value) => {
        this.plugin.settings.unfurlEnabled = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Auto-unfurl on paste").setDesc("Automatically convert pasted URLs to titled links").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.unfurlOnPaste).onChange(async (value) => {
        this.plugin.settings.unfurlOnPaste = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Default format").setDesc("Default format when auto-unfurling pasted URLs").addDropdown(
      (dropdown) => dropdown.addOption("link", "Markdown link").addOption("card", "Link card").setValue(this.plugin.settings.defaultFormat).onChange(async (value) => {
        this.plugin.settings.defaultFormat = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Request timeout").setDesc("Timeout for fetching URL metadata (milliseconds)").addText(
      (text) => text.setPlaceholder("10000").setValue(String(this.plugin.settings.unfurlTimeout)).onChange(async (value) => {
        const num = parseInt(value, 10);
        if (!isNaN(num) && num > 0) {
          this.plugin.settings.unfurlTimeout = num;
          await this.plugin.saveSettings();
        }
      })
    );
    containerEl.createEl("h3", { text: "Cache" });
    new import_obsidian3.Setting(containerEl).setName("Enable cache").setDesc("Cache fetched metadata for faster access and offline use").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.cacheEnabled).onChange(async (value) => {
        this.plugin.settings.cacheEnabled = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Cache TTL").setDesc("How long to keep cached metadata (hours)").addText(
      (text) => text.setPlaceholder("168").setValue(String(this.plugin.settings.cacheTTL)).onChange(async (value) => {
        const num = parseInt(value, 10);
        if (!isNaN(num) && num > 0) {
          this.plugin.settings.cacheTTL = num;
          await this.plugin.saveSettings();
        }
      })
    );
    const stats = this.plugin.unfurlService.getCacheStats();
    new import_obsidian3.Setting(containerEl).setName("Cache statistics").setDesc(`Memory: ${stats.memorySize} entries | Persistent: ${stats.persistentSize} entries`).addButton(
      (btn) => btn.setButtonText("Clear cache").onClick(async () => {
        await this.plugin.unfurlService.clearCache();
        new import_obsidian3.Notice("Link cache cleared");
        this.display();
      })
    );
    containerEl.createEl("h3", { text: "Sidebar" });
    new import_obsidian3.Setting(containerEl).setName("Show sidebar by default").setDesc("Open the link sidebar when Obsidian starts").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showSidebarByDefault).onChange(async (value) => {
        this.plugin.settings.showSidebarByDefault = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Recent history limit").setDesc("Number of items to show in the Recent History section").addText(
      (text) => text.setPlaceholder("25").setValue(String(this.plugin.settings.recentHistoryLimit)).onChange(async (value) => {
        const num = parseInt(value, 10);
        if (!isNaN(num) && num > 0 && num <= 100) {
          this.plugin.settings.recentHistoryLimit = num;
          await this.plugin.saveSettings();
        }
      })
    );
    containerEl.createEl("h3", { text: "Authenticated Domains" });
    containerEl.createEl("p", {
      cls: "setting-item-description",
      text: "Domains that require authentication are skipped during unfurling. One domain per line."
    });
    new import_obsidian3.Setting(containerEl).setName("Auth domains").setDesc("Domains that require login (skipped during unfurling)").addTextArea(
      (text) => text.setPlaceholder("slack.com\nnotion.so").setValue(this.plugin.settings.authDomains.join("\n")).onChange(async (value) => {
        this.plugin.settings.authDomains = value.split("\n").map((d) => d.trim()).filter((d) => d.length > 0);
        await this.plugin.saveSettings();
      })
    );
  }
};
