/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => LinkCommandPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  unfurlEnabled: true,
  unfurlTimeout: 1e4,
  autoExpandUrls: true,
  // Auto-convert new URLs to markdown links
  cacheEnabled: true,
  cacheTTL: 168,
  // 7 days
  authDomains: [
    "slack.com",
    "app.slack.com",
    "notion.so",
    "docs.google.com",
    "drive.google.com",
    "sheets.google.com",
    "mail.google.com",
    "calendar.google.com",
    "linear.app",
    "figma.com",
    "www.figma.com",
    "miro.com",
    "trello.com",
    "asana.com",
    "jira.atlassian.com",
    "confluence.atlassian.com"
  ],
  showSidebarByDefault: true,
  recentHistoryLimit: 10,
  redditLinkFormat: "title_subreddit"
};

// src/UrlMetadataCache.ts
var CACHE_VERSION = 1;
var UrlMetadataCache = class {
  constructor(ttlHours, maxMemorySize, onSave) {
    this.memoryCache = /* @__PURE__ */ new Map();
    this.persistentData = null;
    this.ttlMs = ttlHours * 60 * 60 * 1e3;
    this.maxMemorySize = maxMemorySize;
    this.onSave = onSave;
  }
  /**
   * Load persistent cache from plugin data
   */
  async loadFromStorage(data) {
    if (!data || data.version !== CACHE_VERSION) {
      this.persistentData = { version: CACHE_VERSION, entries: {} };
      return;
    }
    this.persistentData = data;
    const now = Date.now();
    let changed = false;
    for (const [url, metadata] of Object.entries(this.persistentData.entries)) {
      if (this.isExpired(metadata, now)) {
        delete this.persistentData.entries[url];
        changed = true;
      }
    }
    if (changed) {
      await this.savePersistent();
    }
  }
  /**
   * Get metadata from cache (memory first, then persistent)
   */
  get(url) {
    var _a;
    const now = Date.now();
    const memoryEntry = this.memoryCache.get(url);
    if (memoryEntry && !this.isExpired(memoryEntry, now)) {
      return memoryEntry;
    }
    if ((_a = this.persistentData) == null ? void 0 : _a.entries[url]) {
      const persistentEntry = this.persistentData.entries[url];
      if (!this.isExpired(persistentEntry, now)) {
        this.setMemory(url, persistentEntry);
        return persistentEntry;
      }
    }
    return null;
  }
  /**
   * Store metadata in both memory and persistent cache
   */
  async set(url, metadata, sourcePage) {
    if (sourcePage) {
      const existing = this.get(url);
      const existingPages = (existing == null ? void 0 : existing.sourcePages) || [];
      if (!existingPages.includes(sourcePage)) {
        metadata.sourcePages = [...existingPages, sourcePage];
      } else {
        metadata.sourcePages = existingPages;
      }
    }
    this.setMemory(url, metadata);
    if (this.persistentData) {
      this.persistentData.entries[url] = metadata;
      await this.savePersistent();
    }
  }
  /**
   * Clear all caches
   */
  async clear() {
    this.memoryCache.clear();
    if (this.persistentData) {
      this.persistentData.entries = {};
      await this.savePersistent();
    }
  }
  /**
   * Get cache statistics
   */
  getStats() {
    return {
      memorySize: this.memoryCache.size,
      persistentSize: this.persistentData ? Object.keys(this.persistentData.entries).length : 0
    };
  }
  /**
   * Update TTL setting
   */
  setTTL(hours) {
    this.ttlMs = hours * 60 * 60 * 1e3;
  }
  /**
   * Get all cached entries sorted by fetchedAt (most recent first)
   */
  getRecentEntries(limit) {
    const entries = [];
    const now = Date.now();
    if (this.persistentData) {
      for (const metadata of Object.values(this.persistentData.entries)) {
        if (!this.isExpired(metadata, now)) {
          entries.push(metadata);
        }
      }
    }
    entries.sort((a, b) => b.fetchedAt - a.fetchedAt);
    return entries.slice(0, limit);
  }
  /**
   * Check if a URL is in the cache (without full get)
   */
  has(url) {
    return this.get(url) !== null;
  }
  setMemory(url, metadata) {
    if (this.memoryCache.size >= this.maxMemorySize) {
      const firstKey = this.memoryCache.keys().next().value;
      if (firstKey) {
        this.memoryCache.delete(firstKey);
      }
    }
    this.memoryCache.set(url, metadata);
  }
  isExpired(metadata, now) {
    return now - metadata.fetchedAt > this.ttlMs;
  }
  async savePersistent() {
    if (this.persistentData) {
      await this.onSave(this.persistentData);
    }
  }
};

// src/UrlMetadataProvider.ts
var import_obsidian = require("obsidian");
function parseHtmlMetadata(html, baseUrl) {
  const doc = new DOMParser().parseFromString(html, "text/html");
  const getMeta = (selectors) => {
    for (const selector of selectors) {
      const el = doc.querySelector(selector);
      if (el) {
        const content = el.getAttribute("content") || el.textContent;
        if (content == null ? void 0 : content.trim())
          return content.trim();
      }
    }
    return null;
  };
  const resolveUrl = (relative) => {
    if (!relative)
      return null;
    try {
      return new URL(relative, baseUrl).href;
    } catch (e) {
      return relative;
    }
  };
  const getFavicon = () => {
    const iconSelectors = [
      'link[rel="icon"]',
      'link[rel="shortcut icon"]',
      'link[rel="apple-touch-icon"]'
    ];
    for (const selector of iconSelectors) {
      const el = doc.querySelector(selector);
      if (el) {
        const href = el.getAttribute("href");
        if (href)
          return resolveUrl(href);
      }
    }
    try {
      return new URL("/favicon.ico", baseUrl).href;
    } catch (e) {
      return null;
    }
  };
  return {
    title: getMeta([
      'meta[property="og:title"]',
      'meta[name="twitter:title"]',
      "title"
    ]),
    description: getMeta([
      'meta[property="og:description"]',
      'meta[name="twitter:description"]',
      'meta[name="description"]'
    ]),
    image: resolveUrl(getMeta([
      'meta[property="og:image"]',
      'meta[name="twitter:image"]',
      'meta[name="twitter:image:src"]'
    ])),
    favicon: getFavicon(),
    siteName: getMeta(['meta[property="og:site_name"]']),
    type: getMeta(['meta[property="og:type"]']),
    publishedDate: getMeta([
      'meta[property="article:published_time"]',
      'meta[name="date"]',
      'meta[name="pubdate"]'
    ])
  };
}
var HtmlMetadataProvider = class {
  constructor() {
    this.name = "html";
    this.priority = 100;
  }
  // Low priority - runs after any API-based providers
  canHandle(_url) {
    return true;
  }
  async fetch(url, timeout) {
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url,
        method: "GET",
        headers: {
          "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
          "Accept-Language": "en-US,en;q=0.5"
        },
        throw: false
      });
      if (response.status >= 400) {
        console.warn(`[Link Command] HTTP ${response.status} for ${url}`);
        return {
          success: false,
          error: response.status === 401 || response.status === 403 ? "auth_required" : "network_error",
          errorMessage: `HTTP ${response.status}`
        };
      }
      const html = response.text;
      const parsed = parseHtmlMetadata(html, url);
      const loginIndicators = [
        "sign in",
        "log in",
        "login",
        "authenticate",
        "authorization required",
        "access denied"
      ];
      const titleLower = (parsed.title || "").toLowerCase();
      if (loginIndicators.some((ind) => titleLower.includes(ind))) {
        return {
          success: false,
          error: "auth_required",
          errorMessage: "Page requires authentication"
        };
      }
      const metadata = {
        url,
        title: parsed.title || null,
        description: parsed.description || null,
        image: parsed.image || null,
        favicon: parsed.favicon || null,
        siteName: parsed.siteName || null,
        type: parsed.type || null,
        publishedDate: parsed.publishedDate || null,
        fetchedAt: Date.now()
      };
      return {
        success: true,
        metadata
      };
    } catch (error) {
      console.error(`[Link Command] Fetch error for ${url}:`, error);
      return {
        success: false,
        error: "network_error",
        errorMessage: error instanceof Error ? error.message : "Unknown error"
      };
    }
  }
};
var AuthDomainProvider = class {
  constructor(authDomains) {
    this.name = "auth-domain";
    this.priority = 1;
    this.authDomains = authDomains;
  }
  updateDomains(domains) {
    this.authDomains = domains;
  }
  canHandle(url) {
    try {
      const hostname = new URL(url).hostname;
      return this.authDomains.some(
        (domain) => hostname === domain || hostname.endsWith("." + domain)
      );
    } catch (e) {
      return false;
    }
  }
  async fetch(url, _timeout) {
    let hostname;
    try {
      hostname = new URL(url).hostname;
    } catch (e) {
      hostname = "unknown";
    }
    return {
      success: false,
      error: "auth_required",
      errorMessage: `${hostname} requires authentication. Add an API provider or remove from auth domains list.`
    };
  }
};

// src/providers/RedditProvider.ts
var import_obsidian2 = require("obsidian");
var RedditProvider = class {
  constructor() {
    this.name = "reddit";
    this.priority = 10;
  }
  // Higher priority than generic HTML provider
  canHandle(url) {
    try {
      const hostname = new URL(url).hostname;
      return hostname === "reddit.com" || hostname === "www.reddit.com" || hostname === "old.reddit.com" || hostname === "new.reddit.com" || hostname.endsWith(".reddit.com");
    } catch (e) {
      return false;
    }
  }
  async fetch(url, timeout) {
    try {
      const jsonUrl = this.getJsonUrl(url);
      const response = await (0, import_obsidian2.requestUrl)({
        url: jsonUrl,
        method: "GET",
        headers: {
          "Accept": "application/json",
          "User-Agent": "Mozilla/5.0 (compatible; LinkCommand/1.0)"
        },
        throw: false
      });
      if (response.status >= 400) {
        return {
          success: false,
          error: "network_error",
          errorMessage: `HTTP ${response.status}`
        };
      }
      const parsed = this.parseJsonResponse(response.json, url);
      const metadata = {
        url,
        title: parsed.title,
        description: parsed.description,
        image: parsed.image,
        favicon: "https://www.reddit.com/favicon.ico",
        siteName: "Reddit",
        type: parsed.type,
        publishedDate: null,
        fetchedAt: Date.now(),
        subreddit: parsed.subreddit || void 0
      };
      return {
        success: true,
        metadata
      };
    } catch (error) {
      console.error(`[Link Command] Reddit fetch error for ${url}:`, error);
      return {
        success: false,
        error: "network_error",
        errorMessage: error instanceof Error ? error.message : "Unknown error"
      };
    }
  }
  /**
   * Convert a Reddit URL to its JSON API equivalent
   */
  getJsonUrl(url) {
    const parsed = new URL(url);
    parsed.hostname = "www.reddit.com";
    let path = parsed.pathname.replace(/\/$/, "");
    if (!path.endsWith(".json")) {
      path += ".json";
    }
    parsed.pathname = path;
    return parsed.toString();
  }
  /**
   * Extract subreddit from URL path
   */
  extractSubredditFromUrl(url) {
    try {
      const path = new URL(url).pathname;
      const match = path.match(/^\/r\/([^\/]+)/i);
      if (match) {
        return `r/${match[1]}`;
      }
    } catch (e) {
    }
    return null;
  }
  /**
   * Parse Reddit JSON API response
   */
  parseJsonResponse(json, originalUrl) {
    var _a, _b, _c, _d, _e, _f, _g, _h, _i;
    let title = null;
    let description = null;
    let image = null;
    let subreddit = this.extractSubredditFromUrl(originalUrl);
    const isPost = originalUrl.includes("/comments/");
    const type = isPost ? "reddit:post" : "reddit:subreddit";
    try {
      let postData = null;
      if (Array.isArray(json) && json.length > 0) {
        const listing = json[0];
        if ((_c = (_b = (_a = listing == null ? void 0 : listing.data) == null ? void 0 : _a.children) == null ? void 0 : _b[0]) == null ? void 0 : _c.data) {
          postData = listing.data.children[0].data;
        }
      } else if (json && typeof json === "object" && "data" in json) {
        const listing = json;
        if ((_f = (_e = (_d = listing == null ? void 0 : listing.data) == null ? void 0 : _d.children) == null ? void 0 : _e[0]) == null ? void 0 : _f.data) {
          postData = listing.data.children[0].data;
        }
      }
      if (postData) {
        if (typeof postData.title === "string") {
          title = postData.title;
        }
        if (typeof postData.subreddit === "string") {
          subreddit = `r/${postData.subreddit}`;
        } else if (typeof postData.subreddit_name_prefixed === "string") {
          subreddit = postData.subreddit_name_prefixed;
        }
        if (typeof postData.selftext === "string" && postData.selftext.trim()) {
          description = postData.selftext.slice(0, 300);
          if (postData.selftext.length > 300) {
            description += "...";
          }
        }
        if (typeof postData.thumbnail === "string" && postData.thumbnail.startsWith("http") && !postData.thumbnail.includes("thumbs.redditmedia.com")) {
          image = postData.thumbnail;
        }
        if (postData.preview && typeof postData.preview === "object") {
          const preview = postData.preview;
          if ((_i = (_h = (_g = preview.images) == null ? void 0 : _g[0]) == null ? void 0 : _h.source) == null ? void 0 : _i.url) {
            image = preview.images[0].source.url.replace(/&amp;/g, "&");
          }
        }
      }
    } catch (e) {
      console.error("[Link Command] Failed to parse Reddit JSON:", e);
    }
    return {
      title,
      description,
      image,
      type,
      subreddit
    };
  }
};

// src/providers/GoogleSearchProvider.ts
var GoogleSearchProvider = class {
  constructor() {
    this.name = "google-search";
    this.priority = 5;
  }
  // Between AuthDomain (1) and Reddit (10)
  canHandle(url) {
    try {
      const parsed = new URL(url);
      const hostname = parsed.hostname;
      const isGoogle = hostname === "google.com" || hostname === "www.google.com" || hostname.match(/^(www\.)?google\.[a-z]{2,3}(\.[a-z]{2})?$/i) !== null;
      if (!isGoogle)
        return false;
      const isSearchPath = parsed.pathname === "/search" || parsed.pathname.startsWith("/search");
      const hasQuery = parsed.searchParams.has("q");
      return isSearchPath && hasQuery;
    } catch (e) {
      return false;
    }
  }
  async fetch(url, _timeout) {
    try {
      const parsed = new URL(url);
      const query = parsed.searchParams.get("q");
      if (!query) {
        return {
          success: false,
          error: "parse_error",
          errorMessage: "No search query found in URL"
        };
      }
      const decodedQuery = decodeURIComponent(query.replace(/\+/g, " "));
      const metadata = {
        url,
        title: decodedQuery,
        description: `Google search for "${decodedQuery}"`,
        image: null,
        favicon: "https://www.google.com/favicon.ico",
        siteName: "Google",
        type: "search",
        publishedDate: null,
        fetchedAt: Date.now(),
        searchQuery: decodedQuery
      };
      return {
        success: true,
        metadata
      };
    } catch (error) {
      return {
        success: false,
        error: "parse_error",
        errorMessage: error instanceof Error ? error.message : "Failed to parse Google search URL"
      };
    }
  }
};

// src/UrlUnfurlService.ts
var URL_REGEX = /^https?:\/\/[^\s]+$/i;
var UrlUnfurlService = class {
  constructor(settings, onSaveCache) {
    this.providers = [];
    this.settings = settings;
    this.cache = new UrlMetadataCache(
      settings.cacheTTL,
      100,
      // max memory entries
      onSaveCache
    );
    this.authDomainProvider = new AuthDomainProvider(settings.authDomains);
    this.providers.push(this.authDomainProvider);
    this.providers.push(new GoogleSearchProvider());
    this.providers.push(new RedditProvider());
    this.providers.push(new HtmlMetadataProvider());
    this.sortProviders();
  }
  /**
   * Load cached data from storage
   */
  async loadCache(data) {
    await this.cache.loadFromStorage(data);
  }
  /**
   * Update settings
   */
  updateSettings(settings) {
    this.settings = settings;
    this.cache.setTTL(settings.cacheTTL);
    this.authDomainProvider.updateDomains(settings.authDomains);
  }
  /**
   * Register a custom provider (e.g., API-based provider for specific services)
   */
  registerProvider(provider) {
    this.providers.push(provider);
    this.sortProviders();
  }
  /**
   * Unfurl a URL - get its metadata
   * @param sourcePage - Optional file path where this URL was unfurled (for tracking)
   */
  async unfurl(url, forceRefresh = false, sourcePage) {
    if (!this.isValidUrl(url)) {
      return {
        success: false,
        error: "invalid_url",
        errorMessage: "Invalid URL format"
      };
    }
    if (!forceRefresh && this.settings.cacheEnabled) {
      const cached = this.cache.get(url);
      if (cached) {
        if (sourcePage && this.settings.cacheEnabled) {
          await this.cache.set(url, cached, sourcePage);
        }
        return { success: true, metadata: cached };
      }
    }
    const provider = this.providers.find((p) => p.canHandle(url));
    if (!provider) {
      return {
        success: false,
        error: "network_error",
        errorMessage: "No provider available for this URL"
      };
    }
    const result = await provider.fetch(url, this.settings.unfurlTimeout);
    if (result.success && result.metadata && this.settings.cacheEnabled) {
      await this.cache.set(url, result.metadata, sourcePage);
    }
    return result;
  }
  /**
   * Unfurl multiple URLs in parallel
   */
  async unfurlBatch(urls) {
    const results = /* @__PURE__ */ new Map();
    const promises = urls.map(async (url) => {
      const result = await this.unfurl(url);
      results.set(url, result);
    });
    await Promise.all(promises);
    return results;
  }
  /**
   * Check if a string is a valid URL
   */
  isValidUrl(url) {
    if (!URL_REGEX.test(url))
      return false;
    try {
      new URL(url);
      return true;
    } catch (e) {
      return false;
    }
  }
  /**
   * Extract URLs from text
   */
  extractUrls(text) {
    const urlRegex = /https?:\/\/[^\s\]\)]+/g;
    const matches = text.match(urlRegex) || [];
    return matches.map((url) => url.replace(/[.,;:!?)*]+$/, ""));
  }
  /**
   * Get cache statistics
   */
  getCacheStats() {
    return this.cache.getStats();
  }
  /**
   * Clear cache
   */
  async clearCache() {
    await this.cache.clear();
  }
  /**
   * Get recent entries from cache
   */
  getRecentEntries(limit) {
    return this.cache.getRecentEntries(limit);
  }
  /**
   * Check if URL is in cache
   */
  isCached(url) {
    return this.cache.has(url);
  }
  /**
   * Get cached metadata for a URL (without fetching)
   */
  getCached(url) {
    return this.cache.get(url);
  }
  sortProviders() {
    this.providers.sort((a, b) => a.priority - b.priority);
  }
};

// src/LinkSidebarView.ts
var import_obsidian3 = require("obsidian");
var VIEW_TYPE_LINK_SIDEBAR = "link-command-sidebar";
var LinkSidebarView = class extends import_obsidian3.ItemView {
  constructor(leaf, unfurlService, settings, onOpenUrl, onShowAbout, onOpenSettings, onClearHistory) {
    super(leaf);
    this.activeFileListener = null;
    this.renderDebounceTimer = null;
    this.unfurlService = unfurlService;
    this.settings = settings;
    this.onOpenUrl = onOpenUrl;
    this.onShowAbout = onShowAbout;
    this.onOpenSettings = onOpenSettings;
    this.onClearHistory = onClearHistory;
  }
  getViewType() {
    return VIEW_TYPE_LINK_SIDEBAR;
  }
  getDisplayText() {
    return "Links";
  }
  getIcon() {
    return "link";
  }
  async onOpen() {
    this.activeFileListener = () => this.render();
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", this.activeFileListener)
    );
    this.registerEvent(
      this.app.workspace.on("file-open", this.activeFileListener)
    );
    this.registerEvent(
      this.app.workspace.on("editor-change", () => this.debouncedRender())
    );
    await this.render();
  }
  /**
   * Debounced render to avoid excessive re-renders during typing
   */
  debouncedRender() {
    if (this.renderDebounceTimer) {
      clearTimeout(this.renderDebounceTimer);
    }
    this.renderDebounceTimer = setTimeout(() => {
      this.render();
      this.renderDebounceTimer = null;
    }, 300);
  }
  async onClose() {
  }
  updateSettings(settings) {
    this.settings = settings;
    this.render();
  }
  async render() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("link-command-sidebar");
    this.renderHeader(container);
    const content = container.createEl("div", { cls: "link-sidebar-content" });
    const activeFile = this.app.workspace.getActiveFile();
    await this.renderPageLinksSection(content, activeFile);
    this.renderRecentHistorySection(content);
  }
  renderHeader(container) {
    const headerDiv = container.createEl("div", { cls: "link-sidebar-header" });
    const titleEl = headerDiv.createEl("h4", { cls: "link-sidebar-title" });
    const logoEl = titleEl.createEl("span", { cls: "link-command-logo clickable-logo", text: "L\u2318" });
    logoEl.addEventListener("click", () => this.onShowAbout());
    titleEl.appendText(" Link Command");
    const menuBtn = headerDiv.createEl("button", {
      cls: "clickable-icon link-sidebar-menu-btn",
      attr: { "aria-label": "Menu" }
    });
    menuBtn.innerHTML = '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="5" r="1"></circle><circle cx="12" cy="12" r="1"></circle><circle cx="12" cy="19" r="1"></circle></svg>';
    menuBtn.addEventListener("click", (evt) => {
      const menu = new import_obsidian3.Menu();
      menu.addItem((item) => {
        item.setTitle("Refresh").setIcon("refresh-cw").onClick(async () => {
          menuBtn.addClass("rotating");
          await this.render();
          setTimeout(() => menuBtn.removeClass("rotating"), 500);
        });
      });
      menu.addSeparator();
      menu.addItem((item) => {
        item.setTitle("About").setIcon("info").onClick(() => this.onShowAbout());
      });
      menu.addItem((item) => {
        item.setTitle("Settings").setIcon("settings").onClick(() => this.onOpenSettings());
      });
      menu.showAtMouseEvent(evt);
    });
  }
  async renderPageLinksSection(container, activeFile) {
    const section = container.createEl("div", { cls: "link-sidebar-section" });
    const header = section.createEl("div", { cls: "link-sidebar-section-header" });
    header.createEl("span", { text: "Page Links", cls: "link-sidebar-section-title" });
    const listContainer = section.createEl("div", { cls: "link-sidebar-list" });
    if (!activeFile) {
      listContainer.createEl("div", { cls: "link-sidebar-empty", text: "No file open" });
      return;
    }
    const fileContent = await this.app.vault.read(activeFile);
    const pageLinks = this.extractLinksFromContent(fileContent);
    if (pageLinks.length === 0) {
      listContainer.createEl("div", { cls: "link-sidebar-empty", text: "No links in this file" });
      return;
    }
    for (const link of pageLinks) {
      this.renderLinkItem(listContainer, link, activeFile);
    }
  }
  renderRecentHistorySection(container) {
    const section = container.createEl("div", { cls: "link-sidebar-section" });
    const header = section.createEl("div", { cls: "link-sidebar-section-header" });
    header.createEl("span", { text: "Recent History", cls: "link-sidebar-section-title" });
    const listContainer = section.createEl("div", { cls: "link-sidebar-list" });
    const recentEntries = this.unfurlService.getRecentEntries(this.settings.recentHistoryLimit);
    if (recentEntries.length === 0) {
      listContainer.createEl("div", { cls: "link-sidebar-empty", text: "No unfurled links yet" });
      return;
    }
    const clearBtn = header.createEl("button", {
      cls: "clickable-icon link-sidebar-clear-btn",
      attr: { "aria-label": "Clear history" }
    });
    clearBtn.innerHTML = '<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 6h18"></path><path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6"></path><path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2"></path></svg>';
    clearBtn.addEventListener("click", async (e) => {
      e.stopPropagation();
      await this.onClearHistory();
      this.render();
    });
    for (const metadata of recentEntries) {
      this.renderHistoryItem(listContainer, metadata);
    }
  }
  extractLinksFromContent(content) {
    const links = [];
    const urlRegex = /https?:\/\/[^\s\]\)>"']+/g;
    const lines = content.split("\n");
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      let match;
      while ((match = urlRegex.exec(line)) !== null) {
        const url = match[0].replace(/[.,;:!?)*]+$/, "");
        if (!links.some((l) => l.url === url)) {
          const cached = this.unfurlService.getCached(url);
          links.push({
            url,
            lineNumber: i,
            isCached: cached !== null,
            metadata: cached || void 0
          });
        }
      }
    }
    return links;
  }
  renderLinkItem(container, link, activeFile) {
    var _a, _b;
    const item = container.createEl("div", { cls: "link-sidebar-item" });
    if ((_a = link.metadata) == null ? void 0 : _a.favicon) {
      const favicon = item.createEl("img", {
        cls: "link-sidebar-favicon",
        attr: { src: link.metadata.favicon, alt: "" }
      });
      favicon.addEventListener("error", () => {
        favicon.remove();
        item.insertBefore(
          createEl("span", {
            cls: `link-sidebar-status ${link.isCached ? "link-sidebar-status-cached" : "link-sidebar-status-pending"}`,
            attr: { title: link.isCached ? "Unfurled" : "Not unfurled" }
          }),
          item.firstChild
        );
      });
    } else {
      item.createEl("span", {
        cls: `link-sidebar-status ${link.isCached ? "link-sidebar-status-cached" : "link-sidebar-status-pending"}`,
        attr: { title: link.isCached ? "Unfurled" : "Not unfurled" }
      });
    }
    const content = item.createEl("div", { cls: "link-sidebar-item-content" });
    if ((_b = link.metadata) == null ? void 0 : _b.title) {
      content.createEl("div", { cls: "link-sidebar-item-title", text: link.metadata.title });
      if (link.metadata.subreddit) {
        content.createEl("div", { cls: "link-sidebar-item-subreddit", text: link.metadata.subreddit });
      }
      content.createEl("div", { cls: "link-sidebar-item-url", text: this.truncateUrl(link.url) });
    } else {
      content.createEl("div", { cls: "link-sidebar-item-title", text: this.truncateUrl(link.url) });
    }
    const externalBtn = item.createEl("button", {
      cls: "clickable-icon link-sidebar-external-btn",
      attr: { "aria-label": "Open in browser" }
    });
    externalBtn.innerHTML = '<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"></path><polyline points="15 3 21 3 21 9"></polyline><line x1="10" y1="14" x2="21" y2="3"></line></svg>';
    externalBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      window.open(link.url, "_blank");
    });
    item.addEventListener("click", () => {
      window.open(link.url, "_blank");
    });
    item.addEventListener("contextmenu", (e) => {
      e.preventDefault();
      this.showLinkContextMenu(e, link, activeFile);
    });
  }
  renderHistoryItem(container, metadata) {
    const item = container.createEl("div", { cls: "link-sidebar-item link-sidebar-history-item" });
    if (metadata.favicon) {
      const favicon = item.createEl("img", {
        cls: "link-sidebar-favicon",
        attr: { src: metadata.favicon, alt: "" }
      });
      favicon.addEventListener("error", () => favicon.remove());
    } else {
      item.createEl("span", { cls: "link-sidebar-favicon-placeholder" });
    }
    const content = item.createEl("div", { cls: "link-sidebar-item-content" });
    content.createEl("div", {
      cls: "link-sidebar-item-title",
      text: metadata.title || this.truncateUrl(metadata.url)
    });
    if (metadata.subreddit) {
      content.createEl("div", { cls: "link-sidebar-item-subreddit", text: metadata.subreddit });
    }
    const metaRow = content.createEl("div", { cls: "link-sidebar-item-meta" });
    metaRow.createEl("span", { cls: "link-sidebar-item-url", text: this.truncateUrl(metadata.url) });
    if (metadata.sourcePages && metadata.sourcePages.length > 0) {
      const sourceCount = metadata.sourcePages.length;
      const sourceText = sourceCount === 1 ? this.getFileName(metadata.sourcePages[0]) : `${sourceCount} pages`;
      metaRow.createEl("span", { cls: "link-sidebar-item-source", text: `\xB7 ${sourceText}` });
    }
    const timeAgo = this.formatTimeAgo(metadata.fetchedAt);
    metaRow.createEl("span", { cls: "link-sidebar-item-time", text: `\xB7 ${timeAgo}` });
    const externalBtn = item.createEl("button", {
      cls: "clickable-icon link-sidebar-external-btn",
      attr: { "aria-label": "Open in browser" }
    });
    externalBtn.innerHTML = '<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"></path><polyline points="15 3 21 3 21 9"></polyline><line x1="10" y1="14" x2="21" y2="3"></line></svg>';
    externalBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      window.open(metadata.url, "_blank");
    });
    item.addEventListener("click", () => {
      window.open(metadata.url, "_blank");
    });
    item.addEventListener("contextmenu", (e) => {
      e.preventDefault();
      this.showHistoryContextMenu(e, metadata);
    });
  }
  showLinkContextMenu(e, link, activeFile) {
    var _a;
    const menu = new import_obsidian3.Menu();
    menu.addItem((item) => {
      item.setTitle("Unfurl link").setIcon("refresh-cw").onClick(async () => {
        await this.unfurlService.unfurl(link.url, true, activeFile.path);
        this.render();
      });
    });
    menu.addItem((item) => {
      item.setTitle("Copy URL").setIcon("copy").onClick(async () => {
        await navigator.clipboard.writeText(link.url);
      });
    });
    if ((_a = link.metadata) == null ? void 0 : _a.title) {
      menu.addItem((item) => {
        item.setTitle("Copy as markdown link").setIcon("link").onClick(async () => {
          const mdLink = `[${link.metadata.title}](${link.url})`;
          await navigator.clipboard.writeText(mdLink);
        });
      });
    }
    menu.addItem((item) => {
      item.setTitle("Open in browser").setIcon("external-link").onClick(() => {
        window.open(link.url, "_blank");
      });
    });
    menu.showAtMouseEvent(e);
  }
  showHistoryContextMenu(e, metadata) {
    const menu = new import_obsidian3.Menu();
    menu.addItem((item) => {
      item.setTitle("Copy URL").setIcon("copy").onClick(async () => {
        await navigator.clipboard.writeText(metadata.url);
      });
    });
    if (metadata.title) {
      menu.addItem((item) => {
        item.setTitle("Copy as markdown link").setIcon("link").onClick(async () => {
          const mdLink = `[${metadata.title}](${metadata.url})`;
          await navigator.clipboard.writeText(mdLink);
        });
      });
    }
    menu.addItem((item) => {
      item.setTitle("Open in browser").setIcon("external-link").onClick(() => {
        window.open(metadata.url, "_blank");
      });
    });
    if (metadata.sourcePages && metadata.sourcePages.length > 0) {
      menu.addSeparator();
      menu.addItem((item) => {
        item.setTitle("Source pages").setIcon("file-text").setDisabled(true);
      });
      for (const sourcePath of metadata.sourcePages.slice(0, 5)) {
        menu.addItem((item) => {
          item.setTitle(`  ${this.getFileName(sourcePath)}`).onClick(async () => {
            const file = this.app.vault.getAbstractFileByPath(sourcePath);
            if (file instanceof import_obsidian3.TFile) {
              await this.app.workspace.getLeaf().openFile(file);
            }
          });
        });
      }
    }
    menu.showAtMouseEvent(e);
  }
  truncateUrl(url, maxLength = 50) {
    try {
      const parsed = new URL(url);
      const display = parsed.hostname + parsed.pathname;
      if (display.length > maxLength) {
        return display.slice(0, maxLength - 3) + "...";
      }
      return display;
    } catch (e) {
      return url.length > maxLength ? url.slice(0, maxLength - 3) + "..." : url;
    }
  }
  getFileName(path) {
    const parts = path.split("/");
    return parts[parts.length - 1].replace(/\.md$/, "");
  }
  formatTimeAgo(timestamp) {
    const seconds = Math.floor((Date.now() - timestamp) / 1e3);
    if (seconds < 60)
      return "just now";
    if (seconds < 3600)
      return `${Math.floor(seconds / 60)}m ago`;
    if (seconds < 86400)
      return `${Math.floor(seconds / 3600)}h ago`;
    if (seconds < 604800)
      return `${Math.floor(seconds / 86400)}d ago`;
    return new Date(timestamp).toLocaleDateString();
  }
};

// src/UrlFormatToggle.ts
var import_view = require("@codemirror/view");
var import_state = require("@codemirror/state");
var COMMAND_ICON = `<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M18 3a3 3 0 0 0-3 3v12a3 3 0 0 0 3 3 3 3 0 0 0 3-3 3 3 0 0 0-3-3H6a3 3 0 0 0-3 3 3 3 0 0 0 3 3 3 3 0 0 0 3-3V6a3 3 0 0 0-3-3 3 3 0 0 0-3 3 3 3 0 0 0 3 3h12a3 3 0 0 0 3-3 3 3 0 0 0-3-3z"></path></svg>`;
var FormatToggleWidget = class extends import_view.WidgetType {
  constructor(url, currentFormat, from, to) {
    super();
    this.url = url;
    this.currentFormat = currentFormat;
    this.from = from;
    this.to = to;
  }
  toDOM() {
    const btn = document.createElement("span");
    btn.className = "link-format-toggle";
    btn.innerHTML = COMMAND_ICON;
    btn.setAttribute("aria-label", `Toggle link format (currently ${this.currentFormat})`);
    btn.setAttribute("data-url", this.url);
    btn.setAttribute("data-from", String(this.from));
    btn.setAttribute("data-to", String(this.to));
    btn.setAttribute("data-format", this.currentFormat);
    return btn;
  }
  ignoreEvent() {
    return false;
  }
  eq(other) {
    return this.url === other.url && this.currentFormat === other.currentFormat && this.from === other.from && this.to === other.to;
  }
};
function detectFormat(state, url, pos) {
  const doc = state.doc;
  const line = doc.lineAt(pos);
  const lineText = line.text;
  const urlEscaped = url.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const richPattern = new RegExp(`\\[[^\\]]*\\*\\*[^*]+\\*\\*[^\\]]*\\]\\(${urlEscaped}\\)`);
  if (richPattern.test(lineText)) {
    return "rich";
  }
  const linkPattern = new RegExp(`\\]\\(${urlEscaped}\\)`);
  if (linkPattern.test(lineText)) {
    return "link";
  }
  return "url";
}
function findFormatRange(state, url, pos, format) {
  const doc = state.doc;
  const line = doc.lineAt(pos);
  const urlEscaped = url.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  if (format === "url") {
    const urlStart = line.text.indexOf(url);
    if (urlStart >= 0) {
      return {
        from: line.from + urlStart,
        to: line.from + urlStart + url.length
      };
    }
  }
  if (format === "link" || format === "rich") {
    const mdLinkPattern = new RegExp(`\\[([^\\]]*)\\]\\(${urlEscaped}\\)`);
    const match = mdLinkPattern.exec(line.text);
    if (match) {
      return {
        from: line.from + match.index,
        to: line.from + match.index + match[0].length
      };
    }
  }
  return {
    from: pos,
    to: pos + url.length
  };
}
function buildDecorations(state, enabled) {
  if (!enabled) {
    return import_view.Decoration.none;
  }
  const builder = new import_state.RangeSetBuilder();
  const doc = state.doc;
  const urlRegex = /https?:\/\/[^\s\]\)"`'<>]+/g;
  const processed = /* @__PURE__ */ new Set();
  for (let i = 1; i <= doc.lines; i++) {
    const line = doc.line(i);
    const lineText = line.text;
    if (lineText.trim().startsWith("```"))
      continue;
    let match;
    urlRegex.lastIndex = 0;
    while ((match = urlRegex.exec(lineText)) !== null) {
      const url = match[0];
      const urlPos = line.from + match.index;
      const key = `${urlPos}:${url}`;
      if (processed.has(key))
        continue;
      processed.add(key);
      const cleanUrl = url.replace(/[.,;:!?)*]+$/, "");
      const cleanUrlPos = urlPos;
      const cleanUrlEnd = cleanUrlPos + cleanUrl.length;
      const format = detectFormat(state, cleanUrl, cleanUrlPos);
      const range = findFormatRange(state, cleanUrl, cleanUrlPos, format);
      const widgetPos = format === "url" ? cleanUrlEnd : range.to;
      const widget = new FormatToggleWidget(
        cleanUrl,
        format,
        range.from,
        range.to
      );
      const decoration = import_view.Decoration.widget({
        widget,
        side: 1
        // After the position
      });
      builder.add(widgetPos, widgetPos, decoration);
    }
  }
  return builder.finish();
}
function createConfigField(config) {
  return import_state.StateField.define({
    create: () => config,
    update: (value) => value
  });
}
function createFormatToggleExtension(config) {
  const configField = createConfigField(config);
  const decorationField = import_state.StateField.define({
    create(state) {
      return buildDecorations(state, config.enabled);
    },
    update(decorations, tr) {
      const currentConfig = tr.state.field(configField);
      if (tr.docChanged) {
        return buildDecorations(tr.state, currentConfig.enabled);
      }
      return decorations.map(tr.changes);
    },
    provide: (f) => import_view.EditorView.decorations.from(f)
  });
  const clickHandler = import_view.ViewPlugin.fromClass(
    class {
      constructor(view) {
        this.view = view;
      }
      destroy() {
      }
    },
    {
      eventHandlers: {
        click: (event, view) => {
          const target = event.target;
          const toggle = target.closest(".link-format-toggle");
          if (!toggle)
            return false;
          event.preventDefault();
          event.stopPropagation();
          const url = toggle.getAttribute("data-url");
          const from = parseInt(toggle.getAttribute("data-from") || "0", 10);
          const to = parseInt(toggle.getAttribute("data-to") || "0", 10);
          const format = toggle.getAttribute("data-format");
          if (!url)
            return false;
          const currentConfig = view.state.field(configField);
          cycleFormat(view, url, from, to, format, currentConfig);
          return true;
        }
      }
    }
  );
  const autoExpandHandler = import_view.ViewPlugin.fromClass(
    class {
      constructor(view) {
        this.view = view;
        this.pendingUrls = /* @__PURE__ */ new Set();
        this.debounceTimer = null;
      }
      update(update) {
        const currentConfig = update.state.field(configField);
        if (!currentConfig.autoExpand || !update.docChanged)
          return;
        update.transactions.forEach((tr) => {
          if (!tr.docChanged)
            return;
          tr.changes.iterChanges((fromA, toA, fromB, toB, inserted) => {
            const insertedText = inserted.toString();
            const urlRegex = /https?:\/\/[^\s\]\)"`'<>]+/g;
            let match;
            while ((match = urlRegex.exec(insertedText)) !== null) {
              const url = match[0].replace(/[.,;:!?)*]+$/, "");
              const pos = fromB + match.index;
              const format = detectFormat(update.state, url, pos);
              if (format === "url") {
                this.pendingUrls.add(`${pos}:${url}`);
              }
            }
          });
        });
        if (this.pendingUrls.size > 0) {
          if (this.debounceTimer)
            clearTimeout(this.debounceTimer);
          this.debounceTimer = setTimeout(() => {
            this.processUrls(currentConfig);
          }, 500);
        }
      }
      async processUrls(config2) {
        var _a;
        const urlsToProcess = Array.from(this.pendingUrls);
        this.pendingUrls.clear();
        for (const entry of urlsToProcess) {
          const [posStr, url] = entry.split(":", 2);
          const pos = parseInt(posStr, 10);
          const currentFormat = detectFormat(this.view.state, url, pos);
          if (currentFormat !== "url")
            continue;
          const range = findFormatRange(this.view.state, url, pos, "url");
          const docText = this.view.state.doc.sliceString(range.from, range.to);
          if (docText !== url)
            continue;
          const sourcePage = config2.getSourcePage();
          const result = await config2.unfurlService.unfurl(url, false, sourcePage);
          let title = url;
          if (result.success && ((_a = result.metadata) == null ? void 0 : _a.title)) {
            title = result.metadata.title;
          }
          const replacement = `[${title}](${url})`;
          const transaction = this.view.state.update({
            changes: { from: range.from, to: range.to, insert: replacement }
          });
          this.view.dispatch(transaction);
          if (config2.onFormatChange) {
            config2.onFormatChange();
          }
        }
      }
      destroy() {
        if (this.debounceTimer)
          clearTimeout(this.debounceTimer);
      }
    }
  );
  return [configField, decorationField, clickHandler, autoExpandHandler];
}
async function cycleFormat(view, url, from, to, currentFormat, config) {
  const nextFormat = getNextFormat(currentFormat);
  let replacement;
  switch (nextFormat) {
    case "link":
      replacement = await createMarkdownLink(url, config);
      break;
    case "rich":
      replacement = await createRichLink(url, config);
      break;
    case "url":
      replacement = url;
      break;
  }
  const transaction = view.state.update({
    changes: { from, to, insert: replacement }
  });
  view.dispatch(transaction);
  if (config.onFormatChange) {
    config.onFormatChange();
  }
}
function getNextFormat(current) {
  switch (current) {
    case "url":
      return "link";
    case "link":
      return "rich";
    case "rich":
      return "url";
  }
}
async function createMarkdownLink(url, config) {
  var _a;
  const sourcePage = config.getSourcePage();
  const result = await config.unfurlService.unfurl(url, false, sourcePage);
  if (result.success && ((_a = result.metadata) == null ? void 0 : _a.title)) {
    const title = result.metadata.title;
    return `[${title}](${url})`;
  }
  return `[${url}](${url})`;
}
async function createRichLink(url, config) {
  const sourcePage = config.getSourcePage();
  const result = await config.unfurlService.unfurl(url, false, sourcePage);
  let title = url;
  let extra = "";
  if (result.success && result.metadata) {
    const metadata = result.metadata;
    title = metadata.title || url;
    if (metadata.searchQuery) {
      extra = "Google";
    } else if (metadata.subreddit) {
      extra = metadata.subreddit;
    } else {
      try {
        const hostname = new URL(url).hostname.replace(/^www\./, "");
        extra = hostname;
      } catch (e) {
      }
    }
  } else {
    try {
      const hostname = new URL(url).hostname.replace(/^www\./, "");
      extra = hostname;
    } catch (e) {
    }
  }
  if (extra) {
    return `[${title} \xB7 **${extra}**](${url})`;
  }
  return `[${title}](${url})`;
}

// main.ts
var LOGO_PREFIX = "L\u2318";
function showNotice(message, timeout) {
  const fragment = document.createDocumentFragment();
  const logo = document.createElement("span");
  logo.className = "link-command-logo";
  logo.textContent = LOGO_PREFIX;
  fragment.appendChild(logo);
  fragment.appendChild(document.createTextNode(" " + message));
  return new import_obsidian4.Notice(fragment, timeout);
}
var LinkCommandPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.cacheData = null;
    this.sidebarView = null;
  }
  async onload() {
    await this.loadSettings();
    this.unfurlService = new UrlUnfurlService(
      this.settings,
      async (data) => {
        this.cacheData = data;
        await this.saveData({ settings: this.settings, cache: data });
      }
    );
    const savedData = await this.loadData();
    await this.unfurlService.loadCache((savedData == null ? void 0 : savedData.cache) || null);
    this.registerView(
      VIEW_TYPE_LINK_SIDEBAR,
      (leaf) => {
        this.sidebarView = new LinkSidebarView(
          leaf,
          this.unfurlService,
          this.settings,
          (url, lineNumber) => this.navigateToUrl(url, lineNumber),
          () => this.showAbout(),
          () => this.openSettings(),
          async () => {
            await this.unfurlService.clearCache();
            showNotice("Link history cleared");
          }
        );
        return this.sidebarView;
      }
    );
    this.addRibbonIcon("link", "Link Command", () => {
      this.toggleSidebar();
    });
    if (this.settings.showSidebarByDefault) {
      this.app.workspace.onLayoutReady(() => {
        this.activateSidebar();
      });
    }
    this.registerFormatToggleExtension();
    this.addCommand({
      id: "toggle-link-format",
      name: "Toggle link format",
      editorCallback: async (editor) => {
        const url = this.detectUrlAtCursor(editor);
        if (url) {
          await this.cycleFormatAtCursor(editor, url);
        } else {
          showNotice("No URL found at cursor");
        }
      }
    });
    this.addCommand({
      id: "clear-link-cache",
      name: "Clear link cache",
      callback: async () => {
        var _a;
        await this.unfurlService.clearCache();
        showNotice("Link cache cleared");
        (_a = this.sidebarView) == null ? void 0 : _a.render();
      }
    });
    this.addCommand({
      id: "toggle-link-sidebar",
      name: "Toggle link sidebar",
      callback: () => {
        this.toggleSidebar();
      }
    });
    this.addSettingTab(new LinkCommandSettingTab(this.app, this));
  }
  onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_LINK_SIDEBAR);
  }
  /**
   * Activate the sidebar view
   */
  async activateSidebar() {
    const existing = this.app.workspace.getLeavesOfType(VIEW_TYPE_LINK_SIDEBAR);
    if (existing.length > 0) {
      this.app.workspace.revealLeaf(existing[0]);
      return;
    }
    const rightLeaf = this.app.workspace.getRightLeaf(false);
    if (rightLeaf) {
      await rightLeaf.setViewState({
        type: VIEW_TYPE_LINK_SIDEBAR,
        active: true
      });
    }
  }
  /**
   * Toggle the sidebar view
   */
  async toggleSidebar() {
    const existing = this.app.workspace.getLeavesOfType(VIEW_TYPE_LINK_SIDEBAR);
    if (existing.length > 0) {
      existing[0].detach();
    } else {
      await this.activateSidebar();
    }
  }
  /**
   * Navigate to a URL in the active file
   */
  navigateToUrl(url, lineNumber) {
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile)
      return;
    const leaf = this.app.workspace.getLeaf();
    leaf.openFile(activeFile).then(() => {
      const view = leaf.view;
      if (view && "editor" in view) {
        const editor = view.editor;
        if (editor) {
          editor.setCursor({ line: lineNumber, ch: 0 });
          editor.scrollIntoView({ from: { line: lineNumber, ch: 0 }, to: { line: lineNumber, ch: 0 } }, true);
        }
      }
    });
  }
  /**
   * Show the About modal
   */
  showAbout() {
    new AboutModal(this.app, this.manifest.version, this.unfurlService).open();
  }
  /**
   * Open plugin settings
   */
  openSettings() {
    this.app.setting.open();
    this.app.setting.openTabById("link-command");
  }
  async loadSettings() {
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data == null ? void 0 : data.settings);
  }
  async saveSettings() {
    var _a;
    await this.saveData({ settings: this.settings, cache: this.cacheData });
    this.unfurlService.updateSettings(this.settings);
    (_a = this.sidebarView) == null ? void 0 : _a.updateSettings(this.settings);
  }
  /**
   * Format metadata title for display, including subreddit if configured
   */
  formatLinkTitle(metadata, url) {
    if (!metadata.title)
      return url;
    if (metadata.subreddit && this.settings.redditLinkFormat === "title_subreddit") {
      return `${metadata.title} (${metadata.subreddit})`;
    }
    return metadata.title;
  }
  /**
   * Register the inline format toggle extension
   */
  registerFormatToggleExtension() {
    const config = {
      enabled: this.settings.unfurlEnabled,
      autoExpand: this.settings.autoExpandUrls,
      unfurlService: this.unfurlService,
      getSourcePage: () => {
        var _a;
        return (_a = this.app.workspace.getActiveFile()) == null ? void 0 : _a.path;
      },
      onFormatChange: () => {
        var _a;
        (_a = this.sidebarView) == null ? void 0 : _a.render();
      }
    };
    const extension = createFormatToggleExtension(config);
    this.registerEditorExtension(extension);
  }
  /**
   * Detect if cursor is on a URL and return it
   */
  detectUrlAtCursor(editor) {
    const cursor = editor.getCursor();
    const line = editor.getLine(cursor.line);
    const urlRegex = /https?:\/\/[^\s\]\)]+/g;
    let match;
    while ((match = urlRegex.exec(line)) !== null) {
      const start = match.index;
      const end = start + match[0].length;
      if (cursor.ch >= start && cursor.ch <= end) {
        return match[0];
      }
    }
    const selection = editor.getSelection();
    if (selection && this.unfurlService.isValidUrl(selection.trim())) {
      return selection.trim();
    }
    return null;
  }
  /**
   * Cycle through formats at cursor (URL -> Link -> Rich -> URL)
   */
  async cycleFormatAtCursor(editor, url) {
    var _a, _b, _c, _d;
    const cursor = editor.getCursor();
    const line = editor.getLine(cursor.line);
    const urlEscaped = url.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const richPattern = new RegExp(`\\[[^\\]]*\\*\\*[^*]+\\*\\*[^\\]]*\\]\\(${urlEscaped}\\)`);
    const linkPattern = new RegExp(`\\[([^\\]]*)\\]\\(${urlEscaped}\\)`);
    const isRichLink = richPattern.test(line);
    const isMarkdownLink = linkPattern.test(line);
    const activeFile = this.app.workspace.getActiveFile();
    const result = await this.unfurlService.unfurl(url, false, activeFile == null ? void 0 : activeFile.path);
    let replacement;
    let from;
    let to;
    if (isRichLink) {
      const match = linkPattern.exec(line);
      if (match) {
        from = { line: cursor.line, ch: match.index };
        to = { line: cursor.line, ch: match.index + match[0].length };
        replacement = url;
      } else {
        return;
      }
    } else if (isMarkdownLink) {
      const match = linkPattern.exec(line);
      if (match) {
        from = { line: cursor.line, ch: match.index };
        to = { line: cursor.line, ch: match.index + match[0].length };
        const title = result.success && ((_a = result.metadata) == null ? void 0 : _a.title) || url;
        let extra = "";
        if (result.success && ((_b = result.metadata) == null ? void 0 : _b.subreddit)) {
          extra = result.metadata.subreddit;
        } else {
          try {
            extra = new URL(url).hostname.replace(/^www\./, "");
          } catch (e) {
          }
        }
        replacement = extra ? `[${title} \xB7 **${extra}**](${url})` : `[${title}](${url})`;
      } else {
        return;
      }
    } else {
      const urlIndex = line.indexOf(url);
      if (urlIndex >= 0) {
        from = { line: cursor.line, ch: urlIndex };
        to = { line: cursor.line, ch: urlIndex + url.length };
        const title = result.success && ((_c = result.metadata) == null ? void 0 : _c.title) ? this.formatLinkTitle(result.metadata, url) : url;
        replacement = `[${title}](${url})`;
      } else {
        return;
      }
    }
    editor.replaceRange(replacement, from, to);
    (_d = this.sidebarView) == null ? void 0 : _d.render();
  }
};
var LinkCommandSettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Link Command Settings" });
    const aboutSection = containerEl.createEl("div", { cls: "link-command-about-section" });
    const aboutHeader = aboutSection.createEl("div", { cls: "about-header" });
    aboutHeader.createEl("span", { cls: "link-command-logo about-logo", text: "L\u2318" });
    aboutHeader.createEl("span", { cls: "about-title", text: "Link Command" });
    aboutSection.createEl("p", {
      cls: "about-blurb",
      text: "URL unfurling for Obsidian. Fetch link titles and descriptions, insert as markdown links or rich previews."
    });
    aboutSection.createEl("p", { cls: "about-version", text: `Version ${this.plugin.manifest.version}` });
    const aboutDetails = aboutSection.createEl("div", { cls: "about-details" });
    aboutDetails.createEl("span", { text: "By Bruce Alderson" });
    aboutDetails.appendText(" \xB7 ");
    aboutDetails.createEl("a", {
      text: "GitHub",
      href: "https://github.com/robotpony/obsidian-plugins"
    });
    containerEl.createEl("h3", { text: "Sidebar" });
    new import_obsidian4.Setting(containerEl).setName("Show sidebar by default").setDesc("Open the link sidebar when Obsidian starts").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showSidebarByDefault).onChange(async (value) => {
        this.plugin.settings.showSidebarByDefault = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Recent history limit").setDesc("Number of items to show in the Recent History section").addText(
      (text) => text.setPlaceholder("25").setValue(String(this.plugin.settings.recentHistoryLimit)).onChange(async (value) => {
        const num = parseInt(value, 10);
        if (!isNaN(num) && num > 0 && num <= 100) {
          this.plugin.settings.recentHistoryLimit = num;
          await this.plugin.saveSettings();
        }
      })
    );
    containerEl.createEl("h3", { text: "Unfurling" });
    new import_obsidian4.Setting(containerEl).setName("Enable inline format toggle").setDesc("Show toggle buttons next to URLs to cycle between formats (URL, Link, Rich Link). Button appears on hover.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.unfurlEnabled).onChange(async (value) => {
        this.plugin.settings.unfurlEnabled = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Auto-expand URLs").setDesc("Automatically convert new URLs to markdown links with fetched titles").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoExpandUrls).onChange(async (value) => {
        this.plugin.settings.autoExpandUrls = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Request timeout").setDesc("Timeout for fetching URL metadata (milliseconds)").addText(
      (text) => text.setPlaceholder("10000").setValue(String(this.plugin.settings.unfurlTimeout)).onChange(async (value) => {
        const num = parseInt(value, 10);
        if (!isNaN(num) && num > 0) {
          this.plugin.settings.unfurlTimeout = num;
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Reddit link format").setDesc("How to format Reddit links when unfurling").addDropdown(
      (dropdown) => dropdown.addOption("title", "Title only").addOption("title_subreddit", "Title + subreddit").setValue(this.plugin.settings.redditLinkFormat).onChange(async (value) => {
        this.plugin.settings.redditLinkFormat = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "Cache" });
    new import_obsidian4.Setting(containerEl).setName("Enable cache").setDesc("Cache fetched metadata for faster access and offline use").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.cacheEnabled).onChange(async (value) => {
        this.plugin.settings.cacheEnabled = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Cache TTL").setDesc("How long to keep cached metadata (hours)").addText(
      (text) => text.setPlaceholder("168").setValue(String(this.plugin.settings.cacheTTL)).onChange(async (value) => {
        const num = parseInt(value, 10);
        if (!isNaN(num) && num > 0) {
          this.plugin.settings.cacheTTL = num;
          await this.plugin.saveSettings();
        }
      })
    );
    const stats = this.plugin.unfurlService.getCacheStats();
    new import_obsidian4.Setting(containerEl).setName("Cache statistics").setDesc(`Memory: ${stats.memorySize} entries | Persistent: ${stats.persistentSize} entries`).addButton(
      (btn) => btn.setButtonText("Clear cache").onClick(async () => {
        await this.plugin.unfurlService.clearCache();
        showNotice("Link cache cleared");
        this.display();
      })
    );
    containerEl.createEl("h3", { text: "Authenticated Domains" });
    containerEl.createEl("p", {
      cls: "setting-item-description",
      text: "Domains that require authentication are skipped during unfurling. One domain per line."
    });
    new import_obsidian4.Setting(containerEl).setName("Auth domains").setDesc("Domains that require login (skipped during unfurling)").addTextArea(
      (text) => text.setPlaceholder("slack.com\nnotion.so").setValue(this.plugin.settings.authDomains.join("\n")).onChange(async (value) => {
        this.plugin.settings.authDomains = value.split("\n").map((d) => d.trim()).filter((d) => d.length > 0);
        await this.plugin.saveSettings();
      })
    );
  }
};
var AboutModal = class extends import_obsidian4.Modal {
  constructor(app, version, unfurlService) {
    super(app);
    this.version = version;
    this.unfurlService = unfurlService;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("link-command-about-modal");
    const header = contentEl.createEl("div", { cls: "about-header" });
    header.createEl("span", { cls: "link-command-logo about-logo", text: "L\u2318" });
    header.createEl("h2", { text: "Link Command" });
    contentEl.createEl("p", { cls: "about-version", text: `Version ${this.version}` });
    contentEl.createEl("p", {
      cls: "about-blurb",
      text: "URL unfurling for Obsidian. Paste a link, get the title."
    });
    const stats = this.unfurlService.getCacheStats();
    const statsEl = contentEl.createEl("div", { cls: "about-stats" });
    statsEl.createEl("p", { text: `Cached links: ${stats.persistentSize}` });
    statsEl.createEl("p", { text: `Memory cache: ${stats.memorySize}` });
    const details = contentEl.createEl("div", { cls: "about-details" });
    details.createEl("p", { text: "Author: Bruce Alderson" });
    const repoLink = details.createEl("p");
    repoLink.appendText("Repository: ");
    repoLink.createEl("a", {
      text: "github.com/robotpony/obsidian-plugins",
      href: "https://github.com/robotpony/obsidian-plugins"
    });
    details.createEl("p", { text: "Made in \u{1F1E8}\u{1F1E6}", cls: "about-made-in" });
  }
  onClose() {
    this.contentEl.empty();
  }
};
