/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ClickUpHelpersPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  apiToken: "",
  defaultWorkspaceId: "",
  defaultListId: "",
  releaseNotesListId: "",
  releaseNotesStatusFilter: "Release Notes",
  releaseNotesFolder: "release-notes",
  digestListId: "",
  digestFolder: "ticket-digests",
  lastReviewTimestamp: 0,
  llmEnabled: false,
  llmUrl: "http://localhost:11434",
  llmModel: "llama3",
  releaseNotesPrompt: "You are a technical writer. Given a list of ClickUp tasks with descriptions, comments, and attachment info, produce structured release notes in this exact format:\n\n## v[version] \u2014 [date]\n\n### Features\n- ...\n\n### Bug Fixes\n- ...\n\n### Improvements\n- ...\n\nGroup tasks by type. Be concise. Use plain language.",
  ticketReviewPrompt: "You are a product manager assistant. Given a list of ClickUp tickets, group them by theme and produce a concise digest in this format:\n\n## Ticket Review \u2014 [date]\n### Since: [last review date]\n\n### [Theme]\n- **[Task name]** (status) \u2014 brief summary\n\nFocus on patterns and what matters most."
};

// main.ts
var ClickUpHelpersPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new ClickUpSettingsTab(this.app, this));
    console.log("ClickUp Helpers loaded");
  }
  onunload() {
    console.log("ClickUp Helpers unloaded");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var ClickUpSettingsTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "ClickUp Helpers" });
    new import_obsidian.Setting(containerEl).setName("API token").setDesc("Your ClickUp personal API token.").addText(
      (text) => text.setPlaceholder("pk_...").setValue(this.plugin.settings.apiToken).onChange(async (value) => {
        this.plugin.settings.apiToken = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("p", {
      text: "Additional settings (workspace, lists, LLM) will appear here in Phase 2.",
      cls: "setting-item-description"
    });
  }
};
